PRACTICE=practice
PRACTICE2=practice2

all:	_$(PRACTICE) _$(PRACTICE2)

_$(PRACTICE):
	make -C $(PRACTICE)

_$(PRACTICE2):
	make -C $(PRACTICE2)

clean:
	make -C $(PRACTICE) clean
	make -C $(PRACTICE2) clean
