OBJS=_joi2006yo _joi2006ho _joi2007yo _joi2007ho _joisc2007 _joi2008yo

all:	$(OBJS)

_joi2006yo:
	make -C joi2006yo

_joi2006ho:
	make -C joi2006ho

_joi2007yo:
	make -C joi2007yo

_joi2007ho:
	make -C joi2007ho

_joisc2007:
	make -C joisc2007

_joi2008yo:
	make -C joi2008yo

clean:
	make -C joi2006yo clean
	make -C joi2006ho clean
	make -C joi2007yo clean
	make -C joi2007ho clean
	make -C joisc2007 clean
	make -C joi2007yo clean
