OBJS=_joi2006yo _joi2006ho _joi2007yo _joi2007ho

all:	$(OBJS)

_joi2006yo:
	make -C joi2006yo

_joi2006ho:
	make -C joi2006ho

_joi2007yo:
	make -C joi2007yo

_joi2007ho:
	make -C joi2007ho

clean:
	make -C joi2006yo clean
	make -C joi2006ho clean
	make -C joi2007yo clean
	make -C joi2007ho clean
	