ABC151=abc151
ABC152=abc152
ABC153=abc153
ABC154=abc154
ABC155=abc155
ABC156=abc156
ABC157=abc157
ABC158=abc158
ABC159=abc159
ABC160=abc160
ABC161=abc161
ABC162=abc162
ABC163=abc163
ABC164=abc164
ABC165=abc165
ABC166=abc166
ABC167=abc167
ABC168=abc168
ABC169=abc169
ABC170=abc170
ABC171=abc171
ABC172=abc172
ABC173=abc173
ABC174=abc174
ABC175=abc175
ABC176=abc176
ABC177=abc177
ABC178=abc178
ABC179=abc179
ABC180=abc180
ABC181=abc181
ABC182=abc182
ABC183=abc183
ABC184=abc184
ABC185=abc185
ABC186=abc186
ABC187=abc187
ABC188=abc188
ABC189=abc189
ABC190=abc190
ABC191=abc191
ABC192=abc192
ABC193=abc193
ABC194=abc194
ABC195=abc195
ABC196=abc196
ABC197=abc197
ABC198=abc198
ABC199=abc199
ABC200=abc200

all:	_$(ABC151) _$(ABC152) _$(ABC153) _$(ABC154) _$(ABC155) _$(ABC156) _$(ABC157) _$(ABC158) _$(ABC159) _$(ABC160) _$(ABC161) _$(ABC185) _$(ABC186) _$(ABC187) _$(ABC188) _$(ABC189) _$(ABC190) _$(ABC191) _$(ABC192) _$(ABC193) _$(ABC194) _$(ABC195) _$(ABC196) _$(ABC197) _$(ABC198) _$(ABC199) _$(ABC200)
#all:	_$(ABC151) _$(ABC152) _$(ABC153) _$(ABC154) _$(ABC155) _$(ABC156) _$(ABC157) _$(ABC158) _$(ABC159) _$(ABC160) _$(ABC161) _$(ABC162) _$(ABC163) _$(ABC164) _$(ABC165) _$(ABC166) _$(ABC167) _$(ABC168) _$(ABC169) _$(ABC170) _$(ABC171) _$(ABC172) _$(ABC173) _$(ABC174) _$(ABC175) _$(ABC176) _$(ABC177) _$(ABC178) _$(ABC179) _$(ABC180) _$(ABC181) _$(ABC182) _$(ABC183) _$(ABC184) _$(ABC185) _$(ABC186) _$(ABC187) _$(ABC188) _$(ABC189) _$(ABC190) _$(ABC191) _$(ABC192) _$(ABC193) _$(ABC194) _$(ABC195) _$(ABC196) _$(ABC197) _$(ABC198) _$(ABC199) _$(ABC200)

_$(ABC151):
	make -C $(ABC151)

_$(ABC152):
	make -C $(ABC152)

_$(ABC153):
	make -C $(ABC153)

_$(ABC154):
	make -C $(ABC154)

_$(ABC155):
	make -C $(ABC155)

_$(ABC156):
	make -C $(ABC156)

_$(ABC157):
	make -C $(ABC157)

_$(ABC158):
	make -C $(ABC158)

_$(ABC159):
	make -C $(ABC159)

_$(ABC160):
	make -C $(ABC160)

_$(ABC161):
	make -C $(ABC161)

_$(ABC162):
	make -C $(ABC162)

_$(ABC163):
	make -C $(ABC163)

_$(ABC164):
	make -C $(ABC164)

_$(ABC165):
	make -C $(ABC165)

_$(ABC166):
	make -C $(ABC166)

_$(ABC167):
	make -C $(ABC167)

_$(ABC168):
	make -C $(ABC168)

_$(ABC169):
	make -C $(ABC169)

_$(ABC170):
	make -C $(ABC170)

_$(ABC171):
	make -C $(ABC171)

_$(ABC172):
	make -C $(ABC172)

_$(ABC173):
	make -C $(ABC173)

_$(ABC174):
	make -C $(ABC174)

_$(ABC175):
	make -C $(ABC175)

_$(ABC176):
	make -C $(ABC176)

_$(ABC177):
	make -C $(ABC177)

_$(ABC178):
	make -C $(ABC178)

_$(ABC179):
	make -C $(ABC179)

_$(ABC180):
	make -C $(ABC180)

_$(ABC181):
	make -C $(ABC181)

_$(ABC182):
	make -C $(ABC182)

_$(ABC183):
	make -C $(ABC183)

_$(ABC184):
	make -C $(ABC184)

_$(ABC185):
	make -C $(ABC185)

_$(ABC186):
	make -C $(ABC186)

_$(ABC187):
	make -C $(ABC187)

_$(ABC188):
	make -C $(ABC188)

_$(ABC189):
	make -C $(ABC189)

_$(ABC190):
	make -C $(ABC190)

_$(ABC191):
	make -C $(ABC191)

_$(ABC192):
	make -C $(ABC192)

_$(ABC193):
	make -C $(ABC193)

_$(ABC194):
	make -C $(ABC194)

_$(ABC195):
	make -C $(ABC195)

_$(ABC196):
	make -C $(ABC196)

_$(ABC197):
	make -C $(ABC197)

_$(ABC198):
	make -C $(ABC198)

_$(ABC199):
	make -C $(ABC199)

_$(ABC200):
	make -C $(ABC200)

clean:
	make -C $(ABC151) clean
	make -C $(ABC152) clean
	make -C $(ABC153) clean
	make -C $(ABC154) clean
	make -C $(ABC155) clean
	make -C $(ABC156) clean
	make -C $(ABC157) clean
	make -C $(ABC158) clean
	make -C $(ABC159) clean
	make -C $(ABC160) clean
	make -C $(ABC161) clean
#	make -C $(ABC162) clean
#	make -C $(ABC163) clean
#	make -C $(ABC164) clean
#	make -C $(ABC165) clean
#	make -C $(ABC166) clean
#	make -C $(ABC167) clean
#	make -C $(ABC168) clean
#	make -C $(ABC169) clean
#	make -C $(ABC170) clean
#	make -C $(ABC171) clean
#	make -C $(ABC172) clean
#	make -C $(ABC173) clean
#	make -C $(ABC174) clean
#	make -C $(ABC175) clean
#	make -C $(ABC176) clean
#	make -C $(ABC177) clean
#	make -C $(ABC178) clean
#	make -C $(ABC179) clean
#	make -C $(ABC180) clean
#	make -C $(ABC181) clean
#	make -C $(ABC182) clean
#	make -C $(ABC183) clean
#	make -C $(ABC184) clean
	make -C $(ABC185) clean
	make -C $(ABC186) clean
	make -C $(ABC187) clean
	make -C $(ABC188) clean
	make -C $(ABC189) clean
	make -C $(ABC190) clean
	make -C $(ABC191) clean
	make -C $(ABC192) clean
	make -C $(ABC193) clean
	make -C $(ABC194) clean
	make -C $(ABC195) clean
	make -C $(ABC196) clean
	make -C $(ABC197) clean
	make -C $(ABC198) clean
	make -C $(ABC199) clean
	make -C $(ABC200) clean
