include ../CCOptions
ABC151=abc151
ABC152=abc152
ABC153=abc153
ABC154=abc154
ABC155=abc155
ABC156=abc156
ABC157=abc157
ABC158=abc158
ABC159=abc159
ABC160=abc160
ABC161=abc161
ABC162=abc162
ABC163=abc163
ABC164=abc164
ABC165=abc165
ABC166=abc166
ABC167=abc167
ABC168=abc168
ABC169=abc169
ABC170=abc170
ABC171=abc171
ABC172=abc172
ABC173=abc173
ABC174=abc174
ABC175=abc175
ABC176=abc176
ABC177=abc177
ABC178=abc178
ABC179=abc179
ABC180=abc180
ABC181=abc181
ABC182=abc182
ABC183=abc183
ABC184=abc184
ABC185=abc185
ABC186=abc186
ABC187=abc187
ABC188=abc188
ABC189=abc189
ABC190=abc190
ABC191=abc191
ABC192=abc192
ABC193=abc193
ABC194=abc194
ABC195=abc195
ABC196=abc196
ABC197=abc197
ABC198=abc198
ABC199=abc199
ABC200=abc200
OBJS_ABC151=test_abc151A abc151A test_abc151B abc151B test_abc151C abc151C  test_abc151D abc151D test_abc151E abc151E test_abc151F abc151F
OBJS_ABC152=test_abc152A abc152A test_abc152B abc152B test_abc152C abc152C  test_abc152D abc152D test_abc152E abc152E test_abc152F abc152F
OBJS_ABC153=test_abc153A abc153A test_abc153B abc153B test_abc153C abc153C  test_abc153D abc153D test_abc153E abc153E test_abc153F abc153F
OBJS_ABC154=test_abc154A abc154A test_abc154B abc154B test_abc154C abc154C  test_abc154D abc154D test_abc154E abc154E test_abc154F abc154F
OBJS_ABC155=test_abc155A abc155A test_abc155B abc155B test_abc155C abc155C  test_abc155D abc155D test_abc155E abc155E test_abc155F abc155F
OBJS_ABC156=test_abc156A abc156A test_abc156B abc156B test_abc156C abc156C  test_abc156D abc156D test_abc156E abc156E test_abc156F abc156F
OBJS_ABC157=test_abc157A abc157A test_abc157B abc157B test_abc157C abc157C  test_abc157D abc157D test_abc157E abc157E test_abc157F abc157F
OBJS_ABC158=test_abc158A abc158A test_abc158B abc158B test_abc158C abc158C  test_abc158D abc158D test_abc158E abc158E test_abc158F abc158F
OBJS_ABC159=test_abc159A abc159A test_abc159B abc159B test_abc159C abc159C  test_abc159D abc159D test_abc159E abc159E test_abc159F abc159F
OBJS_ABC160=test_abc160A abc160A test_abc160B abc160B test_abc160C abc160C  test_abc160D abc160D test_abc160E abc160E test_abc160F abc160F
OBJS_ABC161=test_abc161A abc161A test_abc161B abc161B test_abc161C abc161C  test_abc161D abc161D test_abc161E abc161E test_abc161F abc161F
OBJS_ABC162=test_abc162A abc162A test_abc162B abc162B test_abc162C abc162C  test_abc162D abc162D test_abc162E abc162E test_abc162F abc162F
OBJS_ABC163=test_abc163A abc163A test_abc163B abc163B test_abc163C abc163C  test_abc163D abc163D test_abc163E abc163E test_abc163F abc163F
OBJS_ABC164=test_abc164A abc164A test_abc164B abc164B test_abc164C abc164C  test_abc164D abc164D test_abc164E abc164E test_abc164F abc164F
OBJS_ABC165=test_abc165A abc165A test_abc165B abc165B test_abc165C abc165C  test_abc165D abc165D test_abc165E abc165E test_abc165F abc165F
OBJS_ABC166=test_abc166A abc166A test_abc166B abc166B test_abc166C abc166C  test_abc166D abc166D test_abc166E abc166E test_abc166F abc166F
OBJS_ABC167=test_abc167A abc167A test_abc167B abc167B test_abc167C abc167C  test_abc167D abc167D test_abc167E abc167E test_abc167F abc167F
OBJS_ABC168=test_abc168A abc168A test_abc168B abc168B test_abc168C abc168C  test_abc168D abc168D test_abc168E abc168E test_abc168F abc168F
OBJS_ABC169=test_abc169A abc169A test_abc169B abc169B test_abc169C abc169C  test_abc169D abc169D test_abc169E abc169E test_abc169F abc169F
OBJS_ABC170=test_abc170A abc170A test_abc170B abc170B test_abc170C abc170C  test_abc170D abc170D test_abc170E abc170E test_abc170F abc170F
OBJS_ABC171=test_abc171A abc171A test_abc171B abc171B test_abc171C abc171C  test_abc171D abc171D test_abc171E abc171E test_abc171F abc171F
OBJS_ABC172=test_abc172A abc172A test_abc172B abc172B test_abc172C abc172C  test_abc172D abc172D test_abc172E abc172E test_abc172F abc172F
OBJS_ABC173=test_abc173A abc173A test_abc173B abc173B test_abc173C abc173C  test_abc173D abc173D test_abc173E abc173E test_abc173F abc173F
OBJS_ABC174=test_abc174A abc174A test_abc174B abc174B test_abc174C abc174C  test_abc174D abc174D test_abc174E abc174E test_abc174F abc174F
OBJS_ABC175=test_abc175A abc175A test_abc175B abc175B test_abc175C abc175C  test_abc175D abc175D test_abc175E abc175E test_abc175F abc175F
OBJS_ABC176=test_abc176A abc176A test_abc176B abc176B test_abc176C abc176C  test_abc176D abc176D test_abc176E abc176E test_abc176F abc176F
OBJS_ABC177=test_abc177A abc177A test_abc177B abc177B test_abc177C abc177C  test_abc177D abc177D test_abc177E abc177E test_abc177F abc177F
OBJS_ABC178=test_abc178A abc178A test_abc178B abc178B test_abc178C abc178C  test_abc178D abc178D test_abc178E abc178E test_abc178F abc178F
OBJS_ABC179=test_abc179A abc179A test_abc179B abc179B test_abc179C abc179C  test_abc179D abc179D test_abc179E abc179E test_abc179F abc179F
OBJS_ABC180=test_abc180A abc180A test_abc180B abc180B test_abc180C abc180C  test_abc180D abc180D test_abc180E abc180E test_abc180F abc180F
OBJS_ABC181=test_abc181A abc181A test_abc181B abc181B test_abc181C abc181C  test_abc181D abc181D test_abc181E abc181E test_abc181F abc181F
OBJS_ABC182=test_abc182A abc182A test_abc182B abc182B test_abc182C abc182C  test_abc182D abc182D test_abc182E abc182E test_abc182F abc182F
OBJS_ABC183=test_abc183A abc183A test_abc183B abc183B test_abc183C abc183C  test_abc183D abc183D test_abc183E abc183E test_abc183F abc183F
OBJS_ABC184=test_abc184A abc184A test_abc184B abc184B test_abc184C abc184C  test_abc184D abc184D test_abc184E abc184E test_abc184F abc184F
OBJS_ABC185=test_abc185A abc185A test_abc185B abc185B test_abc185C abc185C  test_abc185D abc185D test_abc185E abc185E test_abc185F abc185F test_abc185F別回答 abc185F別回答
OBJS_ABC186=test_abc186A abc186A test_abc186B abc186B test_abc186C abc186C  test_abc186D abc186D test_abc186E abc186E test_abc186F abc186F
OBJS_ABC187=test_abc187A abc187A test_abc187B abc187B test_abc187C abc187C  test_abc187D abc187D test_abc187E abc187E test_abc187F abc187F
OBJS_ABC188=test_abc188A abc188A test_abc188B abc188B test_abc188C abc188C  test_abc188D abc188D test_abc188E abc188E test_abc188F abc188F
OBJS_ABC189=test_abc189A abc189A test_abc189B abc189B test_abc189C abc189C  test_abc189D abc189D test_abc189E abc189E test_abc189F abc189F
OBJS_ABC190=test_abc190A abc190A test_abc190B abc190B test_abc190C abc190C  test_abc190D abc190D test_abc190E abc190E test_abc190F abc190F
OBJS_ABC191=test_abc191A abc191A test_abc191B abc191B test_abc191C abc191C  test_abc191D abc191D test_abc191E abc191E test_abc191F abc191F
OBJS_ABC192=test_abc192A abc192A test_abc192B abc192B test_abc192C abc192C  test_abc192D abc192D test_abc192E abc192E test_abc192F abc192F
OBJS_ABC193=test_abc193A abc193A test_abc193B abc193B test_abc193C abc193C  test_abc193D abc193D test_abc193E abc193E test_abc193F abc193F
OBJS_ABC194=test_abc194A abc194A test_abc194B abc194B test_abc194C abc194C  test_abc194D abc194D test_abc194E abc194E test_abc194F abc194F
OBJS_ABC195=test_abc195A abc195A test_abc195B abc195B test_abc195C abc195C  test_abc195D abc195D test_abc195E abc195E test_abc195F abc195F
OBJS_ABC196=test_abc196A abc196A test_abc196B abc196B test_abc196C abc196C  test_abc196D abc196D test_abc196E abc196E test_abc196F abc196F
OBJS_ABC197=test_abc197A abc197A test_abc197B abc197B test_abc197C abc197C  test_abc197D abc197D test_abc197E abc197E test_abc197F abc197F
OBJS_ABC198=test_abc198A abc198A test_abc198B abc198B test_abc198C abc198C  test_abc198D abc198D test_abc198E abc198E test_abc198F abc198F
OBJS_ABC199=test_abc199A abc199A test_abc199B abc199B test_abc199C abc199C  test_abc199D abc199D test_abc199E abc199E test_abc199F abc199F
OBJS_ABC200=test_abc200A abc200A test_abc200B abc200B test_abc200C abc200C  test_abc200D abc200D test_abc200E abc200E test_abc200F abc200F

all:	$(ABC185) $(ABC186) $(ABC187) $(ABC188)
#all:	$(ABC151) $(ABC152) $(ABC153) $(ABC154) $(ABC155) $(ABC156) $(ABC157) $(ABC158) $(ABC159) $(ABC160) $(ABC161) $(ABC162) $(ABC163) $(ABC164) $(ABC165) $(ABC166) $(ABC167) $(ABC168) $(ABC169) $(ABC170) $(ABC171) $(ABC172) $(ABC173) $(ABC174) $(ABC175) $(ABC176) $(ABC177) $(ABC178) $(ABC179) $(ABC180) $(ABC181) $(ABC182) $(ABC183) $(ABC184) $(ABC185) $(ABC186) $(ABC187) $(ABC188) $(ABC189) $(ABC190) $(ABC191) $(ABC192) $(ABC193) $(ABC194) $(ABC195) $(ABC196) $(ABC197) $(ABC198) $(ABC199) $(ABC200)

abc151:	$(OBJS_ABC151)

abc152:	$(OBJS_ABC152)

abc153:	$(OBJS_ABC153)

abc154:	$(OBJS_ABC154)

abc155:	$(OBJS_ABC155)

abc156:	$(OBJS_ABC156)

abc157:	$(OBJS_ABC157)

abc158:	$(OBJS_ABC158)

abc159:	$(OBJS_ABC159)

abc160:	$(OBJS_ABC160)

abc161:	$(OBJS_ABC161)

abc162:	$(OBJS_ABC162)

abc163:	$(OBJS_ABC163)

abc164:	$(OBJS_ABC164)

abc165:	$(OBJS_ABC165)

abc166:	$(OBJS_ABC166)

abc167:	$(OBJS_ABC167)

abc168:	$(OBJS_ABC168)

abc169:	$(OBJS_ABC169)

abc170:	$(OBJS_ABC170)

abc171:	$(OBJS_ABC171)

abc172:	$(OBJS_ABC172)

abc173:	$(OBJS_ABC173)

abc174:	$(OBJS_ABC174)

abc175:	$(OBJS_ABC175)

abc176:	$(OBJS_ABC176)

abc177:	$(OBJS_ABC177)

abc178:	$(OBJS_ABC178)

abc179:	$(OBJS_ABC179)

abc180:	$(OBJS_ABC180)

abc181:	$(OBJS_ABC181)

abc182:	$(OBJS_ABC182)

abc183:	$(OBJS_ABC183)

abc184:	$(OBJS_ABC184)

abc185:	$(OBJS_ABC185)

abc186:	$(OBJS_ABC186)

abc187:	$(OBJS_ABC187)

abc188:	$(OBJS_ABC188)

abc189:	$(OBJS_ABC189)

abc190:	$(OBJS_ABC190)

abc191:	$(OBJS_ABC191)

abc192:	$(OBJS_ABC192)

abc193:	$(OBJS_ABC193)

abc194:	$(OBJS_ABC194)

abc195:	$(OBJS_ABC195)

abc196:	$(OBJS_ABC196)

abc197:	$(OBJS_ABC197)

abc198:	$(OBJS_ABC198)

abc199:	$(OBJS_ABC199)

abc200:	$(OBJS_ABC200)

test_abc185A:	$(TEST_DIR)/$(ABC185)/test_abc185A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc185A:	$(SRC_DIR)/$(ABC185)/abc185A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc185B:	$(TEST_DIR)/$(ABC185)/test_abc185B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc185B:	$(SRC_DIR)/$(ABC185)/abc185B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc185C:	$(TEST_DIR)/$(ABC185)/test_abc185C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc185C:	$(SRC_DIR)/$(ABC185)/abc185C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc185D:	$(TEST_DIR)/$(ABC185)/test_abc185D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc185D:	$(SRC_DIR)/$(ABC185)/abc185D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc185E:	$(TEST_DIR)/$(ABC185)/test_abc185E.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc185E:	$(SRC_DIR)/$(ABC185)/abc185E.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc185F:	$(TEST_DIR)/$(ABC185)/test_abc185F.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc185F:	$(SRC_DIR)/$(ABC185)/abc185F.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc185F別回答:	$(TEST_DIR)/$(ABC185)/test_abc185F別回答.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc185F別回答:	$(SRC_DIR)/$(ABC185)/abc185F別回答.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc186A:	$(TEST_DIR)/$(ABC186)/test_abc186A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc186A:	$(SRC_DIR)/$(ABC186)/abc186A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc186B:	$(TEST_DIR)/$(ABC186)/test_abc186B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc186B:	$(SRC_DIR)/$(ABC186)/abc186B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc186C:	$(TEST_DIR)/$(ABC186)/test_abc186C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc186C:	$(SRC_DIR)/$(ABC186)/abc186C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc186D:	$(TEST_DIR)/$(ABC186)/test_abc186D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc186D:	$(SRC_DIR)/$(ABC186)/abc186D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc186E:	$(TEST_DIR)/$(ABC186)/test_abc186E.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc186E:	$(SRC_DIR)/$(ABC186)/abc186E.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc186F:	$(TEST_DIR)/$(ABC186)/test_abc186F.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc186F:	$(SRC_DIR)/$(ABC186)/abc186F.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc187A:	$(TEST_DIR)/$(ABC187)/test_abc187A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc187A:	$(SRC_DIR)/$(ABC187)/abc187A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc187B:	$(TEST_DIR)/$(ABC187)/test_abc187B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc187B:	$(SRC_DIR)/$(ABC187)/abc187B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc187C:	$(TEST_DIR)/$(ABC187)/test_abc187C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc187C:	$(SRC_DIR)/$(ABC187)/abc187C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc187D:	$(TEST_DIR)/$(ABC187)/test_abc187D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc187D:	$(SRC_DIR)/$(ABC187)/abc187D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc187E:	$(TEST_DIR)/$(ABC187)/test_abc187E.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc187E:	$(SRC_DIR)/$(ABC187)/abc187E.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc187F:	$(TEST_DIR)/$(ABC187)/test_abc187F.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc187F:	$(SRC_DIR)/$(ABC187)/abc187F.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc188A:	$(TEST_DIR)/$(ABC188)/test_abc188A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc188A:	$(SRC_DIR)/$(ABC188)/abc188A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc188B:	$(TEST_DIR)/$(ABC188)/test_abc188B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc188B:	$(SRC_DIR)/$(ABC188)/abc188B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc188C:	$(TEST_DIR)/$(ABC188)/test_abc188C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc188C:	$(SRC_DIR)/$(ABC188)/abc188C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc188D:	$(TEST_DIR)/$(ABC188)/test_abc188D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc188D:	$(SRC_DIR)/$(ABC188)/abc188D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc188E:	$(TEST_DIR)/$(ABC188)/test_abc188E.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc188E:	$(SRC_DIR)/$(ABC188)/abc188E.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc188F:	$(TEST_DIR)/$(ABC188)/test_abc188F.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc188F:	$(SRC_DIR)/$(ABC188)/abc188F.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

clean:
	rm -f $(OBJS_ABC151) $(OBJS_ABC152) $(OBJS_ABC153) $(OBJS_ABC154) $(OBJS_ABC155) $(OBJS_ABC156) $(OBJS_ABC157) $(OBJS_ABC158) $(OBJS_ABC159) $(OBJS_ABC160) $(OBJS_ABC161) $(OBJS_ABC162) $(OBJS_ABC163) $(OBJS_ABC164) $(OBJS_ABC165) $(OBJS_ABC166) $(OBJS_ABC167) $(OBJS_ABC168) $(OBJS_ABC169) $(OBJS_ABC170) $(OBJS_ABC171) $(OBJS_ABC172) $(OBJS_ABC173) $(OBJS_ABC174) $(OBJS_ABC175) $(OBJS_ABC176) $(OBJS_ABC177) $(OBJS_ABC178) $(OBJS_ABC179) $(OBJS_ABC180) $(OBJS_ABC181) $(OBJS_ABC182) $(OBJS_ABC183) $(OBJS_ABC184) $(OBJS_ABC185) $(OBJS_ABC186) $(OBJS_ABC187) $(OBJS_ABC188) $(OBJS_ABC189) $(OBJS_ABC190) $(OBJS_ABC191) $(OBJS_ABC192) $(OBJS_ABC193) $(OBJS_ABC194) $(OBJS_ABC195) $(OBJS_ABC196) $(OBJS_ABC197) $(OBJS_ABC198) $(OBJS_ABC199) $(OBJS_ABC200)
