SRC_DIR=./src
CC=g++
LIBS=-lgtest -lgtest_main
OBJS=test_ex1 ex1 test_ex2 ex2 test_ex3 ex3 test_ex4 ex4 test_ex5 ex5 test_ex6 ex6 test_ex7 ex7 test_ex8 ex8 test_ex9 ex9 test_ex10 ex10 test_ex11 ex11 test_ex12 ex12 test_ex13 ex13 test_ex14 ex14 test_ex15 ex15 test_ex16 ex16 test_ex17 ex17 test_ex18 ex18 test_ex19 ex19 test_ex20 ex20 test_ex21 ex21 test_ex22 ex22 test_ex23 ex23 test_ex24 ex24 test_ex25 ex25 test_ex26 ex26 

all:	$(OBJS)

test_ex1:	$(SRC_DIR)/test_ex1.cpp $(SRC_DIR)/command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex2:	$(SRC_DIR)/test_ex2.cpp $(SRC_DIR)/command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex3:	$(SRC_DIR)/test_ex3.cpp $(SRC_DIR)/command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex4:	$(SRC_DIR)/test_ex4.cpp $(SRC_DIR)/command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex5:	$(SRC_DIR)/test_ex5.cpp $(SRC_DIR)/command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex6:	$(SRC_DIR)/test_ex6.cpp $(SRC_DIR)/command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex7:	$(SRC_DIR)/test_ex7.cpp $(SRC_DIR)/command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex8:	$(SRC_DIR)/test_ex8.cpp $(SRC_DIR)/command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex9:	$(SRC_DIR)/test_ex9.cpp $(SRC_DIR)/command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex10:	test_ex10.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex11:	test_ex11.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex12:	test_ex12.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex13:	test_ex13.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex14:	test_ex14.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex15:	test_ex15.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex16:	test_ex16.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex17:	test_ex17.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex18:	test_ex18.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex19:	test_ex19.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex20:	test_ex20.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex21:	test_ex21.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex22:	test_ex22.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex23:	test_ex23.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex24:	test_ex24.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex25:	test_ex25.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)

test_ex26:	test_ex26.cpp command.h
	$(CC) $(^) -o $(@) $(LIBS)


ex1:	$(SRC_DIR)/ex1.cpp

ex2:	$(SRC_DIR)/ex2.cpp

ex3:	$(SRC_DIR)/ex3.cpp

ex4:	$(SRC_DIR)/ex4.cpp

ex5:	$(SRC_DIR)/ex5.cpp

ex6:	$(SRC_DIR)/ex6.cpp

ex7:	$(SRC_DIR)/ex7.cpp

ex8:	$(SRC_DIR)/ex8.cpp

ex9:	$(SRC_DIR)/ex9.cpp

ex10:	$(SRC_DIR)/ex10.cpp

ex11:	$(SRC_DIR)/ex11.cpp

ex12:	$(SRC_DIR)/ex12.cpp

ex13:	$(SRC_DIR)/ex13.cpp

ex14:	$(SRC_DIR)/ex14.cpp

ex15:	ex15.cpp

ex16:	ex16.cpp

ex17:	ex17.cpp

ex18:	ex18.cpp

ex19:	ex19.cpp

ex20:	ex20.cpp

ex21:	ex21.cpp

ex22:	ex22.cpp

ex23:	ex23.cpp

ex24:	ex24.cpp

ex25:	ex25.cpp

ex26:	ex26.cpp

clean:
	rm -f $(OBJS)
