SRC_DIR=./src
TEST_DIR=./test
CC=g++
CFLAGS=-Og -g
LIBS=-lgtest -lgtest_main
OBJS=test_ex1 ex1 test_ex2 ex2 test_ex3 ex3 test_ex4 ex4 test_ex5 ex5 test_ex6 ex6 test_ex7 ex7 test_ex8 ex8 test_ex9 ex9 test_ex10 ex10 test_ex11 ex11 test_ex12 ex12 test_ex13 ex13 test_ex14 ex14 test_ex15 ex15 test_ex16 ex16 test_ex17 ex17 test_ex18 ex18 test_ex19 ex19 test_ex20 ex20 test_ex21 ex21 test_ex22 ex22 test_ex23 ex23 test_ex24 ex24 test_ex25 ex25 test_ex26 ex26 

all:	$(OBJS)

test_ex1:	$(TEST_DIR)/test_ex1.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex2:	$(TEST_DIR)/test_ex2.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex3:	$(TEST_DIR)/test_ex3.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex4:	$(TEST_DIR)/test_ex4.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex5:	$(TEST_DIR)/test_ex5.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex6:	$(TEST_DIR)/test_ex6.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex7:	$(TEST_DIR)/test_ex7.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex8:	$(TEST_DIR)/test_ex8.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex9:	$(TEST_DIR)/test_ex9.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex10:	$(TEST_DIR)/test_ex10.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex11:	$(TEST_DIR)/test_ex11.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex12:	$(TEST_DIR)/test_ex12.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex13:	$(TEST_DIR)/test_ex13.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex14:	$(TEST_DIR)/test_ex14.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex15:	$(TEST_DIR)/test_ex15.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex16:	$(TEST_DIR)/test_ex16.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex17:	$(TEST_DIR)/test_ex17.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex18:	$(TEST_DIR)/test_ex18.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex19:	$(TEST_DIR)/test_ex19.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex20:	$(TEST_DIR)/test_ex20.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex21:	$(TEST_DIR)/test_ex21.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex22:	$(TEST_DIR)/test_ex22.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex23:	$(TEST_DIR)/test_ex23.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex24:	$(TEST_DIR)/test_ex24.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex25:	$(TEST_DIR)/test_ex25.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

test_ex26:	$(TEST_DIR)/test_ex26.cpp $(TEST_DIR)/command.h
	$(CC) $(CFLAGS) $(^) -o $(@) $(LIBS)

ex1:	$(SRC_DIR)/ex1.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex2:	$(SRC_DIR)/ex2.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex3:	$(SRC_DIR)/ex3.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex4:	$(SRC_DIR)/ex4.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex5:	$(SRC_DIR)/ex5.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex6:	$(SRC_DIR)/ex6.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex7:	$(SRC_DIR)/ex7.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex8:	$(SRC_DIR)/ex8.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex9:	$(SRC_DIR)/ex9.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex10:	$(SRC_DIR)/ex10.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex11:	$(SRC_DIR)/ex11.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex12:	$(SRC_DIR)/ex12.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex13:	$(SRC_DIR)/ex13.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex14:	$(SRC_DIR)/ex14.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex15:	$(SRC_DIR)/ex15.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex16:	$(SRC_DIR)/ex16.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex17:	$(SRC_DIR)/ex17.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex18:	$(SRC_DIR)/ex18.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex19:	$(SRC_DIR)/ex19.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex20:	$(SRC_DIR)/ex20.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex21:	$(SRC_DIR)/ex21.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex22:	$(SRC_DIR)/ex22.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex23:	$(SRC_DIR)/ex23.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex24:	$(SRC_DIR)/ex24.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex25:	$(SRC_DIR)/ex25.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

ex26:	$(SRC_DIR)/ex26.cpp
	$(CC) $(CFLAGS) $(^) -o $(@)

clean:
	rm -f $(OBJS)
