SRC_DIR=./src
TEST_DIR=./test
CC=g++
CFLAGS=-Og -g
INCLUDE=-I../../include
LIBS=-lgtest -lgtest_main
OBJS=test_problemA problemA test_problemB problemB test_problemC problemC test_problemD problemD test_problemE problemE test_problemF problemF test_problemG problemG test_problemH problemH test_problemI problemI test_problemJ problemJ test_problemK problemK test_problemL problemL

all:	$(OBJS)

test_problemA:	$(TEST_DIR)/test_problemA.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemA:	$(SRC_DIR)/problemA.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemB:	$(TEST_DIR)/test_problemB.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemB:	$(SRC_DIR)/problemB.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemC:	$(TEST_DIR)/test_problemC.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemC:	$(SRC_DIR)/problemC.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemD:	$(TEST_DIR)/test_problemD.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemD:	$(SRC_DIR)/problemD.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemE:	$(TEST_DIR)/test_problemE.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemE:	$(SRC_DIR)/problemE.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemF:	$(TEST_DIR)/test_problemF.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemF:	$(SRC_DIR)/problemF.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemG:	$(TEST_DIR)/test_problemG.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemG:	$(SRC_DIR)/problemG.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemH:	$(TEST_DIR)/test_problemH.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemH:	$(SRC_DIR)/problemH.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemI:	$(TEST_DIR)/test_problemI.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemI:	$(SRC_DIR)/problemI.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemJ:	$(TEST_DIR)/test_problemJ.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemJ:	$(SRC_DIR)/problemJ.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemK:	$(TEST_DIR)/test_problemK.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemK:	$(SRC_DIR)/problemK.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problemL:	$(TEST_DIR)/test_problemL.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problemL:	$(SRC_DIR)/problemL.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

clean:
	rm -f $(OBJS)
