ABC201=abc201
ABC202=abc202
ABC203=abc203
ABC204=abc204
ABC205=abc205
ABC206=abc206
ABC207=abc207
ABC208=abc208
ABC209=abc209
ABC210=abc210
ABC211=abc211
ABC212=abc212
ABC213=abc213
ABC214=abc214
ABC215=abc215
ABC216=abc216
ABC217=abc217
ABC218=abc218
ABC219=abc219
ABC220=abc220
ABC221=abc221
ABC222=abc222
ABC223=abc223
ABC224=abc224
ABC225=abc225
ABC226=abc226
ABC227=abc227
ABC228=abc228
ABC229=abc229
ABC230=abc230
ABC231=abc231
ABC232=abc232
ABC233=abc233
ABC234=abc234
ABC235=abc235
ABC236=abc236
ABC237=abc237
ABC238=abc238
ABC239=abc239
ABC240=abc240
ABC241=abc241
ABC242=abc242
ABC243=abc243
ABC244=abc244
ABC245=abc245
ABC246=abc246
ABC247=abc247
ABC248=abc248
ABC249=abc249
ABC250=abc250

all:	_$(ABC201) _$(ABC202) _$(ABC203) _$(ABC204) _$(ABC205) _$(ABC206) _$(ABC207) \
	_$(ABC208) _$(ABC209) _$(ABC210) _$(ABC211) _$(ABC212) _$(ABC213) _$(ABC214) \
	_$(ABC215) _$(ABC216) _$(ABC217) _$(ABC218) _$(ABC219) _$(ABC220) _$(ABC221) \
	_$(ABC222) _$(ABC223) _$(ABC224) _$(ABC225) _$(ABC226) _$(ABC227) _$(ABC228) \
	_$(ABC229) _$(ABC230) _$(ABC231) _$(ABC232) _$(ABC233) #_$(ABC234) _$(ABC235) \
	#_$(ABC236) _$(ABC237) _$(ABC238) _$(ABC239) _$(ABC240) _$(ABC241) _$(ABC242) \
	#_$(ABC243) _$(ABC244) _$(ABC245) _$(ABC246) _$(ABC247) _$(ABC248) _$(ABC249) \
	#_$(ABC250)

_$(ABC201):
	make -C $(ABC201)

_$(ABC202):
	make -C $(ABC202)

_$(ABC203):
	make -C $(ABC203)

_$(ABC204):
	make -C $(ABC204)

_$(ABC205):
	make -C $(ABC205)

_$(ABC206):
	make -C $(ABC206)

_$(ABC207):
	make -C $(ABC207)

_$(ABC208):
	make -C $(ABC208)

_$(ABC209):
	make -C $(ABC209)

_$(ABC210):
	make -C $(ABC210)

_$(ABC211):
	make -C $(ABC211)

_$(ABC212):
	make -C $(ABC212)

_$(ABC213):
	make -C $(ABC213)

_$(ABC214):
	make -C $(ABC214)

_$(ABC215):
	make -C $(ABC215)

_$(ABC216):
	make -C $(ABC216)

_$(ABC217):
	make -C $(ABC217)

_$(ABC218):
	make -C $(ABC218)

_$(ABC219):
	make -C $(ABC219)

_$(ABC220):
	make -C $(ABC220)

_$(ABC221):
	make -C $(ABC221)

_$(ABC222):
	make -C $(ABC222)

_$(ABC223):
	make -C $(ABC223)

_$(ABC224):
	make -C $(ABC224)

_$(ABC225):
	make -C $(ABC225)

_$(ABC226):
	make -C $(ABC226)

_$(ABC227):
	make -C $(ABC227)

_$(ABC228):
	make -C $(ABC228)

_$(ABC229):
	make -C $(ABC229)

_$(ABC230):
	make -C $(ABC230)

_$(ABC231):
	make -C $(ABC231)

_$(ABC232):
	make -C $(ABC232)

_$(ABC233):
	make -C $(ABC233)

_$(ABC234):
	make -C $(ABC234)

_$(ABC235):
	make -C $(ABC235)

_$(ABC236):
	make -C $(ABC236)

_$(ABC237):
	make -C $(ABC237)

_$(ABC238):
	make -C $(ABC238)

_$(ABC239):
	make -C $(ABC239)

_$(ABC240):
	make -C $(ABC240)

_$(ABC241):
	make -C $(ABC241)

_$(ABC242):
	make -C $(ABC242)

_$(ABC243):
	make -C $(ABC243)

_$(ABC244):
	make -C $(ABC244)

_$(ABC245):
	make -C $(ABC245)

_$(ABC246):
	make -C $(ABC246)

_$(ABC247):
	make -C $(ABC247)

_$(ABC248):
	make -C $(ABC248)

_$(ABC249):
	make -C $(ABC249)

_$(ABC250):
	make -C $(ABC250)

clean:
	make -C $(ABC201) clean
	make -C $(ABC202) clean
	make -C $(ABC203) clean
	make -C $(ABC204) clean
	make -C $(ABC205) clean
	make -C $(ABC206) clean
	make -C $(ABC207) clean
	make -C $(ABC208) clean
	make -C $(ABC209) clean
	make -C $(ABC210) clean
	make -C $(ABC211) clean
	make -C $(ABC212) clean
	make -C $(ABC213) clean
	make -C $(ABC214) clean
	make -C $(ABC215) clean
	make -C $(ABC216) clean
	make -C $(ABC217) clean
	make -C $(ABC218) clean
	make -C $(ABC219) clean
	make -C $(ABC220) clean
	make -C $(ABC221) clean
	make -C $(ABC222) clean
	make -C $(ABC223) clean
	make -C $(ABC224) clean
	make -C $(ABC225) clean
	make -C $(ABC226) clean
	make -C $(ABC227) clean
	make -C $(ABC228) clean
	make -C $(ABC229) clean
	make -C $(ABC230) clean
	make -C $(ABC231) clean
	make -C $(ABC232) clean
	make -C $(ABC233) clean
#	make -C $(ABC234) clean
#	make -C $(ABC235) clean
#	make -C $(ABC236) clean
#	make -C $(ABC237) clean
#	make -C $(ABC238) clean
#	make -C $(ABC239) clean
#	make -C $(ABC240) clean
#	make -C $(ABC241) clean
#	make -C $(ABC242) clean
#	make -C $(ABC243) clean
#	make -C $(ABC244) clean
#	make -C $(ABC245) clean
#	make -C $(ABC246) clean
#	make -C $(ABC247) clean
#	make -C $(ABC248) clean
#	make -C $(ABC249) clean
#	make -C $(ABC250) clean
