ABC001=abc001
ABC002=abc002
ABC003=abc003
ABC004=abc004
ABC005=abc005
ABC006=abc006
ABC007=abc007
ABC008=abc008
ABC009=abc009
ABC010=abc010
ABC011=abc011
ABC012=abc012
ABC013=abc013
ABC014=abc014
ABC015=abc015
ABC016=abc016
ABC017=abc017
ABC018=abc018
ABC019=abc019
ABC020=abc020
ABC021=abc021
ABC022=abc022
ABC023=abc023
ABC024=abc024
ABC025=abc025
ABC026=abc026
ABC027=abc027
ABC028=abc028
ABC029=abc029
ABC030=abc030
ABC031=abc031
ABC032=abc032
ABC033=abc033
ABC034=abc034
ABC035=abc035
ABC036=abc036
ABC037=abc037
ABC038=abc038
ABC039=abc039
ABC040=abc040
ABC041=abc041
ABC042=abc042
ABC043=abc043
ABC044=abc044
ABC045=abc045
ABC046=abc046
ABC047=abc047
ABC048=abc048
ABC049=abc049
ABC050=abc050

all:	_$(ABC001) _$(ABC002) _$(ABC003) _$(ABC004) _$(ABC005) _$(ABC006) _$(ABC007) \
	_$(ABC008) _$(ABC009) _$(ABC010) _$(ABC011) _$(ABC012) _$(ABC013) _$(ABC014) \
	_$(ABC015) _$(ABC016) _$(ABC017) _$(ABC018) _$(ABC019) _$(ABC020) _$(ABC021) \
	_$(ABC022) _$(ABC023) _$(ABC024) _$(ABC025) _$(ABC026) _$(ABC027) _$(ABC028) \
	_$(ABC029) _$(ABC030) _$(ABC031) _$(ABC032) _$(ABC033) _$(ABC034) _$(ABC035) \
	_$(ABC036) _$(ABC037) _$(ABC038) _$(ABC039) _$(ABC040) _$(ABC041) _$(ABC042) \
	_$(ABC043) _$(ABC044) _$(ABC045) _$(ABC046) #_$(ABC047) _$(ABC048) _$(ABC049) \
	_$(ABC050)

_$(ABC001):
	make -C $(ABC001)

_$(ABC002):
	make -C $(ABC002)

_$(ABC003):
	make -C $(ABC003)

_$(ABC004):
	make -C $(ABC004)

_$(ABC005):
	make -C $(ABC005)

_$(ABC006):
	make -C $(ABC006)

_$(ABC007):
	make -C $(ABC007)

_$(ABC008):
	make -C $(ABC008)

_$(ABC009):
	make -C $(ABC009)

_$(ABC010):
	make -C $(ABC010)

_$(ABC011):
	make -C $(ABC011)

_$(ABC012):
	make -C $(ABC012)

_$(ABC013):
	make -C $(ABC013)

_$(ABC014):
	make -C $(ABC014)

_$(ABC015):
	make -C $(ABC015)

_$(ABC016):
	make -C $(ABC016)

_$(ABC017):
	make -C $(ABC017)

_$(ABC018):
	make -C $(ABC018)

_$(ABC019):
	make -C $(ABC019)

_$(ABC020):
	make -C $(ABC020)

_$(ABC021):
	make -C $(ABC021)

_$(ABC022):
	make -C $(ABC022)

_$(ABC023):
	make -C $(ABC023)

_$(ABC024):
	make -C $(ABC024)

_$(ABC025):
	make -C $(ABC025)

_$(ABC026):
	make -C $(ABC026)

_$(ABC027):
	make -C $(ABC027)

_$(ABC028):
	make -C $(ABC028)

_$(ABC029):
	make -C $(ABC029)

_$(ABC030):
	make -C $(ABC030)

_$(ABC031):
	make -C $(ABC031)

_$(ABC032):
	make -C $(ABC032)

_$(ABC033):
	make -C $(ABC033)

_$(ABC034):
	make -C $(ABC034)

_$(ABC035):
	make -C $(ABC035)

_$(ABC036):
	make -C $(ABC036)

_$(ABC037):
	make -C $(ABC037)

_$(ABC038):
	make -C $(ABC038)

_$(ABC039):
	make -C $(ABC039)

_$(ABC040):
	make -C $(ABC040)

_$(ABC041):
	make -C $(ABC041)

_$(ABC042):
	make -C $(ABC042)

_$(ABC043):
	make -C $(ABC043)

_$(ABC044):
	make -C $(ABC044)

_$(ABC045):
	make -C $(ABC045)

_$(ABC046):
	make -C $(ABC046)

_$(ABC047):
	make -C $(ABC047)

_$(ABC048):
	make -C $(ABC048)

_$(ABC049):
	make -C $(ABC049)

_$(ABC050):
	make -C $(ABC050)

clean:
	make -C $(ABC001) clean
	make -C $(ABC002) clean
	make -C $(ABC003) clean
	make -C $(ABC004) clean
	make -C $(ABC005) clean
	make -C $(ABC006) clean
	make -C $(ABC007) clean
	make -C $(ABC008) clean
	make -C $(ABC009) clean
	make -C $(ABC010) clean
	make -C $(ABC011) clean
	make -C $(ABC012) clean
	make -C $(ABC013) clean
	make -C $(ABC014) clean
	make -C $(ABC015) clean
	make -C $(ABC016) clean
	make -C $(ABC017) clean
	make -C $(ABC018) clean
	make -C $(ABC019) clean
	make -C $(ABC020) clean
	make -C $(ABC021) clean
	make -C $(ABC022) clean
	make -C $(ABC023) clean
	make -C $(ABC024) clean
	make -C $(ABC025) clean
	make -C $(ABC026) clean
	make -C $(ABC027) clean
	make -C $(ABC028) clean
	make -C $(ABC029) clean
	make -C $(ABC030) clean
	make -C $(ABC031) clean
	make -C $(ABC032) clean
	make -C $(ABC033) clean
	make -C $(ABC034) clean
	make -C $(ABC035) clean
	make -C $(ABC036) clean
	make -C $(ABC037) clean
	make -C $(ABC038) clean
	make -C $(ABC039) clean
	make -C $(ABC040) clean
	make -C $(ABC041) clean
	make -C $(ABC042) clean
	make -C $(ABC043) clean
	make -C $(ABC044) clean
	make -C $(ABC045) clean
	make -C $(ABC046) clean
#	make -C $(ABC047) clean
#	make -C $(ABC048) clean
#	make -C $(ABC049) clean
#	make -C $(ABC050) clean
