include ../CCOptions
ABC001=abc001
ABC002=abc002
ABC003=abc003
ABC004=abc004
ABC005=abc005
ABC006=abc006
ABC007=abc007
ABC008=abc008
ABC009=abc009
ABC010=abc010
ABC011=abc011
ABC012=abc012
ABC013=abc013
ABC014=abc014
ABC015=abc015
ABC016=abc016
ABC017=abc017
ABC018=abc018
ABC019=abc019
ABC020=abc020
ABC021=abc021
ABC022=abc022
ABC023=abc023
ABC024=abc024
ABC025=abc025
ABC026=abc026
ABC027=abc027
ABC028=abc028
ABC029=abc029
ABC030=abc030
ABC031=abc031
ABC032=abc032
ABC033=abc033
ABC034=abc034
ABC035=abc035
ABC036=abc036
ABC037=abc037
ABC038=abc038
ABC039=abc039
ABC040=abc040
ABC041=abc041
ABC042=abc042
ABC043=abc043
ABC044=abc044
ABC045=abc045
ABC046=abc046
ABC047=abc047
ABC048=abc048
ABC049=abc049
ABC050=abc050
OBJS_ABC001=test_abc001A abc001A test_abc001B abc001B test_abc001C abc001C test_abc001D abc001D
OBJS_ABC002=test_abc002A abc002A test_abc002B abc002B test_abc002C abc002C test_abc002D abc002D
OBJS_ABC003=test_abc003A abc003A test_abc003B abc003B test_abc003C abc003C test_abc003D abc003D
OBJS_ABC004=test_abc004A abc004A test_abc004B abc004B test_abc004C abc004C test_abc004D abc004D
OBJS_ABC005=test_abc005A abc005A test_abc005B abc005B test_abc005C abc005C test_abc005D abc005D
OBJS_ABC006=test_abc006A abc006A test_abc006B abc006B test_abc006C abc006C test_abc006D abc006D
OBJS_ABC007=test_abc007A abc007A test_abc007B abc007B test_abc007C abc007C test_abc007D abc007D test_abc007D別回答 abc007D別回答
OBJS_ABC008=test_abc008A abc008A test_abc008B abc008B test_abc008C abc008C test_abc008D abc008D
OBJS_ABC009=test_abc009A abc009A test_abc009B abc009B test_abc009C abc009C test_abc009D abc009D
OBJS_ABC010=test_abc010A abc010A test_abc010B abc010B test_abc010C abc010C test_abc010D abc010D
OBJS_ABC011=test_abc011A abc011A test_abc011B abc011B test_abc011C abc011C test_abc011D abc011D
OBJS_ABC012=test_abc012A abc012A test_abc012B abc012B test_abc012C abc012C test_abc012D abc012D
OBJS_ABC013=test_abc013A abc013A test_abc013B abc013B test_abc013C abc013C test_abc013D abc013D
OBJS_ABC014=test_abc014A abc014A test_abc014B abc014B test_abc014C abc014C test_abc014D abc014D
OBJS_ABC015=test_abc015A abc015A test_abc015B abc015B test_abc015C abc015C test_abc015D abc015D
OBJS_ABC016=test_abc016A abc016A test_abc016B abc016B test_abc016C abc016C test_abc016D abc016D
OBJS_ABC017=test_abc017A abc017A test_abc017B abc017B test_abc017C abc017C test_abc017D abc017D
OBJS_ABC018=test_abc018A abc018A test_abc018B abc018B test_abc018C abc018C test_abc018D abc018D
OBJS_ABC019=test_abc019A abc019A test_abc019B abc019B test_abc019C abc019C test_abc019D abc019D
OBJS_ABC020=test_abc020A abc020A test_abc020B abc020B test_abc020C abc020C test_abc020D abc020D
OBJS_ABC021=test_abc021A abc021A test_abc021B abc021B test_abc021C abc021C test_abc021D abc021D
OBJS_ABC022=test_abc022A abc022A test_abc022B abc022B test_abc022C abc022C test_abc022D abc022D
OBJS_ABC023=test_abc023A abc023A test_abc023B abc023B test_abc023C abc023C test_abc023D abc023D
OBJS_ABC024=test_abc024A abc024A test_abc024B abc024B test_abc024C abc024C test_abc024D abc024D
OBJS_ABC025=test_abc025A abc025A test_abc025B abc025B test_abc025C abc025C test_abc025D abc025D
OBJS_ABC026=test_abc026A abc026A test_abc026B abc026B test_abc026C abc026C test_abc026D abc026D
OBJS_ABC027=test_abc027A abc027A test_abc027B abc027B test_abc027C abc027C test_abc027D abc027D
OBJS_ABC028=test_abc028A abc028A test_abc028B abc028B test_abc028C abc028C test_abc028D abc028D
OBJS_ABC029=test_abc029A abc029A test_abc029B abc029B test_abc029C abc029C test_abc029D abc029D
OBJS_ABC030=test_abc030A abc030A test_abc030B abc030B test_abc030C abc030C test_abc030D abc030D
OBJS_ABC031=test_abc031A abc031A test_abc031B abc031B test_abc031C abc031C test_abc031D abc031D
OBJS_ABC032=test_abc032A abc032A test_abc032B abc032B test_abc032C abc032C test_abc032D abc032D
OBJS_ABC033=test_abc033A abc033A test_abc033B abc033B test_abc033C abc033C test_abc033D abc033D
OBJS_ABC034=test_abc034A abc034A test_abc034B abc034B test_abc034C abc034C test_abc034D abc034D
OBJS_ABC035=test_abc035A abc035A test_abc035B abc035B test_abc035C abc035C test_abc035D abc035D
OBJS_ABC036=test_abc036A abc036A test_abc036B abc036B test_abc036C abc036C test_abc036D abc036D
OBJS_ABC037=test_abc037A abc037A test_abc037B abc037B test_abc037C abc037C test_abc037D abc037D
OBJS_ABC038=test_abc038A abc038A test_abc038B abc038B test_abc038C abc038C test_abc038D abc038D
OBJS_ABC039=test_abc039A abc039A test_abc039B abc039B test_abc039C abc039C test_abc039D abc039D
OBJS_ABC040=test_abc040A abc040A test_abc040B abc040B test_abc040C abc040C test_abc040D abc040D
OBJS_ABC041=test_abc041A abc041A test_abc041B abc041B test_abc041C abc041C test_abc041D abc041D
OBJS_ABC042=test_abc042A abc042A test_abc042B abc042B test_abc042C abc042C test_abc042D abc042D
OBJS_ABC043=test_abc043A abc043A test_abc043B abc043B test_abc043C abc043C test_abc043D abc043D
OBJS_ABC044=test_abc044A abc044A test_abc044B abc044B test_abc044C abc044C test_abc044D abc044D
OBJS_ABC045=test_abc045A abc045A test_abc045B abc045B test_abc045C abc045C test_abc045D abc045D
OBJS_ABC046=test_abc046A abc046A test_abc046B abc046B test_abc046C abc046C test_abc046D abc046D
OBJS_ABC047=test_abc047A abc047A test_abc047B abc047B test_abc047C abc047C test_abc047D abc047D
OBJS_ABC048=test_abc048A abc048A test_abc048B abc048B test_abc048C abc048C test_abc048D abc048D
OBJS_ABC049=test_abc049A abc049A test_abc049B abc049B test_abc049C abc049C test_abc049D abc049D
OBJS_ABC050=test_abc050A abc050A test_abc050B abc050B test_abc050C abc050C test_abc050D abc050D

all:	$(ABC001) $(ABC002) $(ABC003) $(ABC004) $(ABC005) $(ABC006) $(ABC007) $(ABC008) $(ABC009) $(ABC010) $(ABC011) $(ABC012) $(ABC013) $(ABC014) $(ABC015) $(ABC016)
#all:	$(ABC001) $(ABC002) $(ABC003) $(ABC004) $(ABC005) $(ABC006) $(ABC007) $(ABC008) $(ABC009) $(ABC010) $(ABC011) $(ABC012) $(ABC013) $(ABC014) $(ABC015) $(ABC016) $(ABC017) $(ABC018) $(ABC019) $(ABC020) $(ABC021) $(ABC022) $(ABC023) $(ABC024) $(ABC025) $(ABC026) $(ABC027) $(ABC028) $(ABC029) $(ABC030) $(ABC031) $(ABC032) $(ABC033) $(ABC034) $(ABC035) $(ABC036) $(ABC037) $(ABC038) $(ABC039) $(ABC040) $(ABC041) $(ABC042) $(ABC043) $(ABC044) $(ABC045) $(ABC046) $(ABC047) $(ABC048) $(ABC049) $(ABC050)

$(ABC001):	$(OBJS_ABC001)

$(ABC002):	$(OBJS_ABC002)

$(ABC003):	$(OBJS_ABC003)

$(ABC004):	$(OBJS_ABC004)

$(ABC005):	$(OBJS_ABC005)

$(ABC006):	$(OBJS_ABC006)

$(ABC007):	$(OBJS_ABC007)

$(ABC008):	$(OBJS_ABC008)

$(ABC009):	$(OBJS_ABC009)

$(ABC010):	$(OBJS_ABC010)

$(ABC011):	$(OBJS_ABC011)

$(ABC012):	$(OBJS_ABC012)

$(ABC013):	$(OBJS_ABC013)

$(ABC014):	$(OBJS_ABC014)

$(ABC015):	$(OBJS_ABC015)

$(ABC016):	$(OBJS_ABC016)

$(ABC017):	$(OBJS_ABC017)

$(ABC018):	$(OBJS_ABC018)

$(ABC019):	$(OBJS_ABC019)

$(ABC020):	$(OBJS_ABC020)

$(ABC021):	$(OBJS_ABC021)

$(ABC022):	$(OBJS_ABC022)

$(ABC023):	$(OBJS_ABC023)

$(ABC024):	$(OBJS_ABC024)

$(ABC025):	$(OBJS_ABC025)

$(ABC026):	$(OBJS_ABC026)

$(ABC027):	$(OBJS_ABC027)

$(ABC028):	$(OBJS_ABC028)

$(ABC029):	$(OBJS_ABC029)

$(ABC030):	$(OBJS_ABC030)

$(ABC031):	$(OBJS_ABC031)

$(ABC032):	$(OBJS_ABC032)

$(ABC033):	$(OBJS_ABC033)

$(ABC034):	$(OBJS_ABC034)

$(ABC035):	$(OBJS_ABC035)

$(ABC036):	$(OBJS_ABC036)

$(ABC037):	$(OBJS_ABC037)

$(ABC038):	$(OBJS_ABC038)

$(ABC039):	$(OBJS_ABC039)

$(ABC040):	$(OBJS_ABC040)

$(ABC041):	$(OBJS_ABC041)

$(ABC042):	$(OBJS_ABC042)

$(ABC043):	$(OBJS_ABC043)

$(ABC044):	$(OBJS_ABC044)

$(ABC045):	$(OBJS_ABC045)

$(ABC046):	$(OBJS_ABC046)

$(ABC047):	$(OBJS_ABC047)

$(ABC048):	$(OBJS_ABC048)

$(ABC049):	$(OBJS_ABC049)

$(ABC050):	$(OBJS_ABC050)

test_abc001A:	$(TEST_DIR)/$(ABC001)/test_abc001A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc001A:	$(SRC_DIR)/$(ABC001)/abc001A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc001B:	$(TEST_DIR)/$(ABC001)/test_abc001B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc001B:	$(SRC_DIR)/$(ABC001)/abc001B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc001C:	$(TEST_DIR)/$(ABC001)/test_abc001C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc001C:	$(SRC_DIR)/$(ABC001)/abc001C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc001D:	$(TEST_DIR)/$(ABC001)/test_abc001D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc001D:	$(SRC_DIR)/$(ABC001)/abc001D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc002A:	$(TEST_DIR)/$(ABC002)/test_abc002A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc002A:	$(SRC_DIR)/$(ABC002)/abc002A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc002B:	$(TEST_DIR)/$(ABC002)/test_abc002B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc002B:	$(SRC_DIR)/$(ABC002)/abc002B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc002C:	$(TEST_DIR)/$(ABC002)/test_abc002C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc002C:	$(SRC_DIR)/$(ABC002)/abc002C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc002D:	$(TEST_DIR)/$(ABC002)/test_abc002D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc002D:	$(SRC_DIR)/$(ABC002)/abc002D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc003A:	$(TEST_DIR)/$(ABC003)/test_abc003A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc003A:	$(SRC_DIR)/$(ABC003)/abc003A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc003B:	$(TEST_DIR)/$(ABC003)/test_abc003B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc003B:	$(SRC_DIR)/$(ABC003)/abc003B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc003C:	$(TEST_DIR)/$(ABC003)/test_abc003C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc003C:	$(SRC_DIR)/$(ABC003)/abc003C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc003D:	$(TEST_DIR)/$(ABC003)/test_abc003D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc003D:	$(SRC_DIR)/$(ABC003)/abc003D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc004A:	$(TEST_DIR)/$(ABC004)/test_abc004A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc004A:	$(SRC_DIR)/$(ABC004)/abc004A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc004B:	$(TEST_DIR)/$(ABC004)/test_abc004B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc004B:	$(SRC_DIR)/$(ABC004)/abc004B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc004C:	$(TEST_DIR)/$(ABC004)/test_abc004C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc004C:	$(SRC_DIR)/$(ABC004)/abc004C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc004D:	$(TEST_DIR)/$(ABC004)/test_abc004D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc004D:	$(SRC_DIR)/$(ABC004)/abc004D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

abc005A:	$(SRC_DIR)/$(ABC005)/abc005A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc005A:	$(TEST_DIR)/$(ABC005)/test_abc005A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc005B:	$(SRC_DIR)/$(ABC005)/abc005B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc005B:	$(TEST_DIR)/$(ABC005)/test_abc005B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc005C:	$(SRC_DIR)/$(ABC005)/abc005C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc005C:	$(TEST_DIR)/$(ABC005)/test_abc005C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc005D:	$(SRC_DIR)/$(ABC005)/abc005D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc005D:	$(TEST_DIR)/$(ABC005)/test_abc005D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc006A:	$(SRC_DIR)/$(ABC006)/abc006A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc006A:	$(TEST_DIR)/$(ABC006)/test_abc006A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc006B:	$(SRC_DIR)/$(ABC006)/abc006B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc006B:	$(TEST_DIR)/$(ABC006)/test_abc006B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc006C:	$(SRC_DIR)/$(ABC006)/abc006C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc006C:	$(TEST_DIR)/$(ABC006)/test_abc006C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc006D:	$(SRC_DIR)/$(ABC006)/abc006D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc006D:	$(TEST_DIR)/$(ABC006)/test_abc006D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc007A:	$(SRC_DIR)/$(ABC007)/abc007A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc007A:	$(TEST_DIR)/$(ABC007)/test_abc007A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc007B:	$(SRC_DIR)/$(ABC007)/abc007B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc007B:	$(TEST_DIR)/$(ABC007)/test_abc007B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc007C:	$(SRC_DIR)/$(ABC007)/abc007C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc007C:	$(TEST_DIR)/$(ABC007)/test_abc007C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc007D:	$(SRC_DIR)/$(ABC007)/abc007D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc007D:	$(TEST_DIR)/$(ABC007)/test_abc007D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc007D別回答:	$(SRC_DIR)/$(ABC007)/abc007D別回答.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc007D別回答:	$(TEST_DIR)/$(ABC007)/test_abc007D別回答.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc008A:	$(SRC_DIR)/$(ABC008)/abc008A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc008A:	$(TEST_DIR)/$(ABC008)/test_abc008A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc008B:	$(SRC_DIR)/$(ABC008)/abc008B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc008B:	$(TEST_DIR)/$(ABC008)/test_abc008B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc008C:	$(SRC_DIR)/$(ABC008)/abc008C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc008C:	$(TEST_DIR)/$(ABC008)/test_abc008C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc008D:	$(SRC_DIR)/$(ABC008)/abc008D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc008D:	$(TEST_DIR)/$(ABC008)/test_abc008D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc009A:	$(SRC_DIR)/$(ABC009)/abc009A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc009A:	$(TEST_DIR)/$(ABC009)/test_abc009A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc009B:	$(SRC_DIR)/$(ABC009)/abc009B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc009B:	$(TEST_DIR)/$(ABC009)/test_abc009B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc009C:	$(SRC_DIR)/$(ABC009)/abc009C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc009C:	$(TEST_DIR)/$(ABC009)/test_abc009C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc009D:	$(SRC_DIR)/$(ABC009)/abc009D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc009D:	$(TEST_DIR)/$(ABC009)/test_abc009D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc010A:	$(SRC_DIR)/$(ABC010)/abc010A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc010A:	$(TEST_DIR)/$(ABC010)/test_abc010A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc010B:	$(SRC_DIR)/$(ABC010)/abc010B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc010B:	$(TEST_DIR)/$(ABC010)/test_abc010B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc010C:	$(SRC_DIR)/$(ABC010)/abc010C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc010C:	$(TEST_DIR)/$(ABC010)/test_abc010C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc010D:	$(SRC_DIR)/$(ABC010)/abc010D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc010D:	$(TEST_DIR)/$(ABC010)/test_abc010D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc011A:	$(SRC_DIR)/$(ABC011)/abc011A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc011A:	$(TEST_DIR)/$(ABC011)/test_abc011A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc011B:	$(SRC_DIR)/$(ABC011)/abc011B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc011B:	$(TEST_DIR)/$(ABC011)/test_abc011B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc011C:	$(SRC_DIR)/$(ABC011)/abc011C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc011C:	$(TEST_DIR)/$(ABC011)/test_abc011C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc011D:	$(SRC_DIR)/$(ABC011)/abc011D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc011D:	$(TEST_DIR)/$(ABC011)/test_abc011D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc012A:	$(SRC_DIR)/$(ABC012)/abc012A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc012A:	$(TEST_DIR)/$(ABC012)/test_abc012A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc012B:	$(SRC_DIR)/$(ABC012)/abc012B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc012B:	$(TEST_DIR)/$(ABC012)/test_abc012B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc012C:	$(SRC_DIR)/$(ABC012)/abc012C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc012C:	$(TEST_DIR)/$(ABC012)/test_abc012C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc012D:	$(SRC_DIR)/$(ABC012)/abc012D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc012D:	$(TEST_DIR)/$(ABC012)/test_abc012D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc013A:	$(SRC_DIR)/$(ABC013)/abc013A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc013A:	$(TEST_DIR)/$(ABC013)/test_abc013A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc013B:	$(SRC_DIR)/$(ABC013)/abc013B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc013B:	$(TEST_DIR)/$(ABC013)/test_abc013B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc013C:	$(SRC_DIR)/$(ABC013)/abc013C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc013C:	$(TEST_DIR)/$(ABC013)/test_abc013C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc013D:	$(SRC_DIR)/$(ABC013)/abc013D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc013D:	$(TEST_DIR)/$(ABC013)/test_abc013D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc014A:	$(SRC_DIR)/$(ABC014)/abc014A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc014A:	$(TEST_DIR)/$(ABC014)/test_abc014A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc014B:	$(SRC_DIR)/$(ABC014)/abc014B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc014B:	$(TEST_DIR)/$(ABC014)/test_abc014B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc014C:	$(SRC_DIR)/$(ABC014)/abc014C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc014C:	$(TEST_DIR)/$(ABC014)/test_abc014C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc014D:	$(SRC_DIR)/$(ABC014)/abc014D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc014D:	$(TEST_DIR)/$(ABC014)/test_abc014D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc015A:	$(SRC_DIR)/$(ABC015)/abc015A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc015A:	$(TEST_DIR)/$(ABC015)/test_abc015A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc015B:	$(SRC_DIR)/$(ABC015)/abc015B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc015B:	$(TEST_DIR)/$(ABC015)/test_abc015B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc015C:	$(SRC_DIR)/$(ABC015)/abc015C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc015C:	$(TEST_DIR)/$(ABC015)/test_abc015C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc015D:	$(SRC_DIR)/$(ABC015)/abc015D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc015D:	$(TEST_DIR)/$(ABC015)/test_abc015D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc016A:	$(SRC_DIR)/$(ABC016)/abc016A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc016A:	$(TEST_DIR)/$(ABC016)/test_abc016A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc016B:	$(SRC_DIR)/$(ABC016)/abc016B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc016B:	$(TEST_DIR)/$(ABC016)/test_abc016B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc016C:	$(SRC_DIR)/$(ABC016)/abc016C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc016C:	$(TEST_DIR)/$(ABC016)/test_abc016C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc016D:	$(SRC_DIR)/$(ABC016)/abc016D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc016D:	$(TEST_DIR)/$(ABC016)/test_abc016D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc017A:	$(SRC_DIR)/$(ABC017)/abc017A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc017A:	$(TEST_DIR)/$(ABC017)/test_abc017A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc017B:	$(SRC_DIR)/$(ABC017)/abc017B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc017B:	$(TEST_DIR)/$(ABC017)/test_abc017B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc017C:	$(SRC_DIR)/$(ABC017)/abc017C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc017C:	$(TEST_DIR)/$(ABC017)/test_abc017C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc017D:	$(SRC_DIR)/$(ABC017)/abc017D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc017D:	$(TEST_DIR)/$(ABC017)/test_abc017D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc018A:	$(SRC_DIR)/$(ABC018)/abc018A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc018A:	$(TEST_DIR)/$(ABC018)/test_abc018A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc018B:	$(SRC_DIR)/$(ABC018)/abc018B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc018B:	$(TEST_DIR)/$(ABC018)/test_abc018B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc018C:	$(SRC_DIR)/$(ABC018)/abc018C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc018C:	$(TEST_DIR)/$(ABC018)/test_abc018C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc018D:	$(SRC_DIR)/$(ABC018)/abc018D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc018D:	$(TEST_DIR)/$(ABC018)/test_abc018D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc019A:	$(SRC_DIR)/$(ABC019)/abc019A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc019A:	$(TEST_DIR)/$(ABC019)/test_abc019A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc019B:	$(SRC_DIR)/$(ABC019)/abc019B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc019B:	$(TEST_DIR)/$(ABC019)/test_abc019B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc019C:	$(SRC_DIR)/$(ABC019)/abc019C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc019C:	$(TEST_DIR)/$(ABC019)/test_abc019C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc019D:	$(SRC_DIR)/$(ABC019)/abc019D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc019D:	$(TEST_DIR)/$(ABC019)/test_abc019D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc020A:	$(SRC_DIR)/$(ABC020)/abc020A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc020A:	$(TEST_DIR)/$(ABC020)/test_abc020A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc020B:	$(SRC_DIR)/$(ABC020)/abc020B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc020B:	$(TEST_DIR)/$(ABC020)/test_abc020B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc020C:	$(SRC_DIR)/$(ABC020)/abc020C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc020C:	$(TEST_DIR)/$(ABC020)/test_abc020C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc020D:	$(SRC_DIR)/$(ABC020)/abc020D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc020D:	$(TEST_DIR)/$(ABC020)/test_abc020D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc021A:	$(SRC_DIR)/$(ABC021)/abc021A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc021A:	$(TEST_DIR)/$(ABC021)/test_abc021A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc021B:	$(SRC_DIR)/$(ABC021)/abc021B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc021B:	$(TEST_DIR)/$(ABC021)/test_abc021B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc021C:	$(SRC_DIR)/$(ABC021)/abc021C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc021C:	$(TEST_DIR)/$(ABC021)/test_abc021C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc021D:	$(SRC_DIR)/$(ABC021)/abc021D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc021D:	$(TEST_DIR)/$(ABC021)/test_abc021D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc022A:	$(SRC_DIR)/$(ABC022)/abc022A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc022A:	$(TEST_DIR)/$(ABC022)/test_abc022A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc022B:	$(SRC_DIR)/$(ABC022)/abc022B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc022B:	$(TEST_DIR)/$(ABC022)/test_abc022B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc022C:	$(SRC_DIR)/$(ABC022)/abc022C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc022C:	$(TEST_DIR)/$(ABC022)/test_abc022C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc022D:	$(SRC_DIR)/$(ABC022)/abc022D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc022D:	$(TEST_DIR)/$(ABC022)/test_abc022D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc023A:	$(SRC_DIR)/$(ABC023)/abc023A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc023A:	$(TEST_DIR)/$(ABC023)/test_abc023A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc023B:	$(SRC_DIR)/$(ABC023)/abc023B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc023B:	$(TEST_DIR)/$(ABC023)/test_abc023B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc023C:	$(SRC_DIR)/$(ABC023)/abc023C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc023C:	$(TEST_DIR)/$(ABC023)/test_abc023C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc023D:	$(SRC_DIR)/$(ABC023)/abc023D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc023D:	$(TEST_DIR)/$(ABC023)/test_abc023D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc024A:	$(SRC_DIR)/$(ABC024)/abc024A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc024A:	$(TEST_DIR)/$(ABC024)/test_abc024A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc024B:	$(SRC_DIR)/$(ABC024)/abc024B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc024B:	$(TEST_DIR)/$(ABC024)/test_abc024B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc024C:	$(SRC_DIR)/$(ABC024)/abc024C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc024C:	$(TEST_DIR)/$(ABC024)/test_abc024C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc024D:	$(SRC_DIR)/$(ABC024)/abc024D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc024D:	$(TEST_DIR)/$(ABC024)/test_abc024D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc025A:	$(SRC_DIR)/$(ABC025)/abc025A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc025A:	$(TEST_DIR)/$(ABC025)/test_abc025A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc025B:	$(SRC_DIR)/$(ABC025)/abc025B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc025B:	$(TEST_DIR)/$(ABC025)/test_abc025B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc025C:	$(SRC_DIR)/$(ABC025)/abc025C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc025C:	$(TEST_DIR)/$(ABC025)/test_abc025C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc025D:	$(SRC_DIR)/$(ABC025)/abc025D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc025D:	$(TEST_DIR)/$(ABC025)/test_abc025D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc026A:	$(SRC_DIR)/$(ABC026)/abc026A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc026A:	$(TEST_DIR)/$(ABC026)/test_abc026A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc026B:	$(SRC_DIR)/$(ABC026)/abc026B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc026B:	$(TEST_DIR)/$(ABC026)/test_abc026B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc026C:	$(SRC_DIR)/$(ABC026)/abc026C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc026C:	$(TEST_DIR)/$(ABC026)/test_abc026C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc026D:	$(SRC_DIR)/$(ABC026)/abc026D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc026D:	$(TEST_DIR)/$(ABC026)/test_abc026D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc027A:	$(SRC_DIR)/$(ABC027)/abc027A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc027A:	$(TEST_DIR)/$(ABC027)/test_abc027A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc027B:	$(SRC_DIR)/$(ABC027)/abc027B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc027B:	$(TEST_DIR)/$(ABC027)/test_abc027B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc027C:	$(SRC_DIR)/$(ABC027)/abc027C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc027C:	$(TEST_DIR)/$(ABC027)/test_abc027C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc027D:	$(SRC_DIR)/$(ABC027)/abc027D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc027D:	$(TEST_DIR)/$(ABC027)/test_abc027D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc028A:	$(SRC_DIR)/$(ABC028)/abc028A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc028A:	$(TEST_DIR)/$(ABC028)/test_abc028A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc028B:	$(SRC_DIR)/$(ABC028)/abc028B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc028B:	$(TEST_DIR)/$(ABC028)/test_abc028B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc028C:	$(SRC_DIR)/$(ABC028)/abc028C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc028C:	$(TEST_DIR)/$(ABC028)/test_abc028C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc028D:	$(SRC_DIR)/$(ABC028)/abc028D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc028D:	$(TEST_DIR)/$(ABC028)/test_abc028D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc029A:	$(SRC_DIR)/$(ABC029)/abc029A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc029A:	$(TEST_DIR)/$(ABC029)/test_abc029A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc029B:	$(SRC_DIR)/$(ABC029)/abc029B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc029B:	$(TEST_DIR)/$(ABC029)/test_abc029B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc029C:	$(SRC_DIR)/$(ABC029)/abc029C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc029C:	$(TEST_DIR)/$(ABC029)/test_abc029C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc029D:	$(SRC_DIR)/$(ABC029)/abc029D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc029D:	$(TEST_DIR)/$(ABC029)/test_abc029D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc030A:	$(SRC_DIR)/$(ABC030)/abc030A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc030A:	$(TEST_DIR)/$(ABC030)/test_abc030A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc030B:	$(SRC_DIR)/$(ABC030)/abc030B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc030B:	$(TEST_DIR)/$(ABC030)/test_abc030B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc030C:	$(SRC_DIR)/$(ABC030)/abc030C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc030C:	$(TEST_DIR)/$(ABC030)/test_abc030C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc030D:	$(SRC_DIR)/$(ABC030)/abc030D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc030D:	$(TEST_DIR)/$(ABC030)/test_abc030D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc031A:	$(SRC_DIR)/$(ABC031)/abc031A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc031A:	$(TEST_DIR)/$(ABC031)/test_abc031A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc031B:	$(SRC_DIR)/$(ABC031)/abc031B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc031B:	$(TEST_DIR)/$(ABC031)/test_abc031B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc031C:	$(SRC_DIR)/$(ABC031)/abc031C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc031C:	$(TEST_DIR)/$(ABC031)/test_abc031C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc031D:	$(SRC_DIR)/$(ABC031)/abc031D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc031D:	$(TEST_DIR)/$(ABC031)/test_abc031D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc032A:	$(SRC_DIR)/$(ABC032)/abc032A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc032A:	$(TEST_DIR)/$(ABC032)/test_abc032A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc032B:	$(SRC_DIR)/$(ABC032)/abc032B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc032B:	$(TEST_DIR)/$(ABC032)/test_abc032B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc032C:	$(SRC_DIR)/$(ABC032)/abc032C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc032C:	$(TEST_DIR)/$(ABC032)/test_abc032C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc032D:	$(SRC_DIR)/$(ABC032)/abc032D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc032D:	$(TEST_DIR)/$(ABC032)/test_abc032D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc033A:	$(SRC_DIR)/$(ABC033)/abc033A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc033A:	$(TEST_DIR)/$(ABC033)/test_abc033A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc033B:	$(SRC_DIR)/$(ABC033)/abc033B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc033B:	$(TEST_DIR)/$(ABC033)/test_abc033B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc033C:	$(SRC_DIR)/$(ABC033)/abc033C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc033C:	$(TEST_DIR)/$(ABC033)/test_abc033C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc033D:	$(SRC_DIR)/$(ABC033)/abc033D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc033D:	$(TEST_DIR)/$(ABC033)/test_abc033D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc034A:	$(SRC_DIR)/$(ABC034)/abc034A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc034A:	$(TEST_DIR)/$(ABC034)/test_abc034A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc034B:	$(SRC_DIR)/$(ABC034)/abc034B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc034B:	$(TEST_DIR)/$(ABC034)/test_abc034B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc034C:	$(SRC_DIR)/$(ABC034)/abc034C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc034C:	$(TEST_DIR)/$(ABC034)/test_abc034C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc034D:	$(SRC_DIR)/$(ABC034)/abc034D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc034D:	$(TEST_DIR)/$(ABC034)/test_abc034D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc035A:	$(SRC_DIR)/$(ABC035)/abc035A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc035A:	$(TEST_DIR)/$(ABC035)/test_abc035A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc035B:	$(SRC_DIR)/$(ABC035)/abc035B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc035B:	$(TEST_DIR)/$(ABC035)/test_abc035B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc035C:	$(SRC_DIR)/$(ABC035)/abc035C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc035C:	$(TEST_DIR)/$(ABC035)/test_abc035C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc035D:	$(SRC_DIR)/$(ABC035)/abc035D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc035D:	$(TEST_DIR)/$(ABC035)/test_abc035D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc036A:	$(SRC_DIR)/$(ABC036)/abc036A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc036A:	$(TEST_DIR)/$(ABC036)/test_abc036A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc036B:	$(SRC_DIR)/$(ABC036)/abc036B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc036B:	$(TEST_DIR)/$(ABC036)/test_abc036B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc036C:	$(SRC_DIR)/$(ABC036)/abc036C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc036C:	$(TEST_DIR)/$(ABC036)/test_abc036C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc036D:	$(SRC_DIR)/$(ABC036)/abc036D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc036D:	$(TEST_DIR)/$(ABC036)/test_abc036D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc037A:	$(SRC_DIR)/$(ABC037)/abc037A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc037A:	$(TEST_DIR)/$(ABC037)/test_abc037A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc037B:	$(SRC_DIR)/$(ABC037)/abc037B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc037B:	$(TEST_DIR)/$(ABC037)/test_abc037B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc037C:	$(SRC_DIR)/$(ABC037)/abc037C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc037C:	$(TEST_DIR)/$(ABC037)/test_abc037C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc037D:	$(SRC_DIR)/$(ABC037)/abc037D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc037D:	$(TEST_DIR)/$(ABC037)/test_abc037D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc038A:	$(SRC_DIR)/$(ABC038)/abc038A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc038A:	$(TEST_DIR)/$(ABC038)/test_abc038A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc038B:	$(SRC_DIR)/$(ABC038)/abc038B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc038B:	$(TEST_DIR)/$(ABC038)/test_abc038B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc038C:	$(SRC_DIR)/$(ABC038)/abc038C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc038C:	$(TEST_DIR)/$(ABC038)/test_abc038C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc038D:	$(SRC_DIR)/$(ABC038)/abc038D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc038D:	$(TEST_DIR)/$(ABC038)/test_abc038D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc039A:	$(SRC_DIR)/$(ABC039)/abc039A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc039A:	$(TEST_DIR)/$(ABC039)/test_abc039A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc039B:	$(SRC_DIR)/$(ABC039)/abc039B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc039B:	$(TEST_DIR)/$(ABC039)/test_abc039B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc039C:	$(SRC_DIR)/$(ABC039)/abc039C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc039C:	$(TEST_DIR)/$(ABC039)/test_abc039C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc039D:	$(SRC_DIR)/$(ABC039)/abc039D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc039D:	$(TEST_DIR)/$(ABC039)/test_abc039D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc040A:	$(SRC_DIR)/$(ABC040)/abc040A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc040A:	$(TEST_DIR)/$(ABC040)/test_abc040A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc040B:	$(SRC_DIR)/$(ABC040)/abc040B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc040B:	$(TEST_DIR)/$(ABC040)/test_abc040B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc040C:	$(SRC_DIR)/$(ABC040)/abc040C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc040C:	$(TEST_DIR)/$(ABC040)/test_abc040C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc040D:	$(SRC_DIR)/$(ABC040)/abc040D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc040D:	$(TEST_DIR)/$(ABC040)/test_abc040D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc041A:	$(SRC_DIR)/$(ABC041)/abc041A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc041A:	$(TEST_DIR)/$(ABC041)/test_abc041A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc041B:	$(SRC_DIR)/$(ABC041)/abc041B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc041B:	$(TEST_DIR)/$(ABC041)/test_abc041B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc041C:	$(SRC_DIR)/$(ABC041)/abc041C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc041C:	$(TEST_DIR)/$(ABC041)/test_abc041C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc041D:	$(SRC_DIR)/$(ABC041)/abc041D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc041D:	$(TEST_DIR)/$(ABC041)/test_abc041D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc042A:	$(SRC_DIR)/$(ABC042)/abc042A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc042A:	$(TEST_DIR)/$(ABC042)/test_abc042A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc042B:	$(SRC_DIR)/$(ABC042)/abc042B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc042B:	$(TEST_DIR)/$(ABC042)/test_abc042B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc042C:	$(SRC_DIR)/$(ABC042)/abc042C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc042C:	$(TEST_DIR)/$(ABC042)/test_abc042C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc042D:	$(SRC_DIR)/$(ABC042)/abc042D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc042D:	$(TEST_DIR)/$(ABC042)/test_abc042D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc043A:	$(SRC_DIR)/$(ABC043)/abc043A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc043A:	$(TEST_DIR)/$(ABC043)/test_abc043A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc043B:	$(SRC_DIR)/$(ABC043)/abc043B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc043B:	$(TEST_DIR)/$(ABC043)/test_abc043B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc043C:	$(SRC_DIR)/$(ABC043)/abc043C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc043C:	$(TEST_DIR)/$(ABC043)/test_abc043C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc043D:	$(SRC_DIR)/$(ABC043)/abc043D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc043D:	$(TEST_DIR)/$(ABC043)/test_abc043D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc044A:	$(SRC_DIR)/$(ABC044)/abc044A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc044A:	$(TEST_DIR)/$(ABC044)/test_abc044A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc044B:	$(SRC_DIR)/$(ABC044)/abc044B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc044B:	$(TEST_DIR)/$(ABC044)/test_abc044B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc044C:	$(SRC_DIR)/$(ABC044)/abc044C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc044C:	$(TEST_DIR)/$(ABC044)/test_abc044C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc044D:	$(SRC_DIR)/$(ABC044)/abc044D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc044D:	$(TEST_DIR)/$(ABC044)/test_abc044D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc045A:	$(SRC_DIR)/$(ABC045)/abc045A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc045A:	$(TEST_DIR)/$(ABC045)/test_abc045A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc045B:	$(SRC_DIR)/$(ABC045)/abc045B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc045B:	$(TEST_DIR)/$(ABC045)/test_abc045B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc045C:	$(SRC_DIR)/$(ABC045)/abc045C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc045C:	$(TEST_DIR)/$(ABC045)/test_abc045C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc045D:	$(SRC_DIR)/$(ABC045)/abc045D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc045D:	$(TEST_DIR)/$(ABC045)/test_abc045D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc046A:	$(SRC_DIR)/$(ABC046)/abc046A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc046A:	$(TEST_DIR)/$(ABC046)/test_abc046A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc046B:	$(SRC_DIR)/$(ABC046)/abc046B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc046B:	$(TEST_DIR)/$(ABC046)/test_abc046B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc046C:	$(SRC_DIR)/$(ABC046)/abc046C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc046C:	$(TEST_DIR)/$(ABC046)/test_abc046C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc046D:	$(SRC_DIR)/$(ABC046)/abc046D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc046D:	$(TEST_DIR)/$(ABC046)/test_abc046D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc047A:	$(SRC_DIR)/$(ABC047)/abc047A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc047A:	$(TEST_DIR)/$(ABC047)/test_abc047A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc047B:	$(SRC_DIR)/$(ABC047)/abc047B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc047B:	$(TEST_DIR)/$(ABC047)/test_abc047B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc047C:	$(SRC_DIR)/$(ABC047)/abc047C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc047C:	$(TEST_DIR)/$(ABC047)/test_abc047C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc047D:	$(SRC_DIR)/$(ABC047)/abc047D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc047D:	$(TEST_DIR)/$(ABC047)/test_abc047D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc048A:	$(SRC_DIR)/$(ABC048)/abc048A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc048A:	$(TEST_DIR)/$(ABC048)/test_abc048A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc048B:	$(SRC_DIR)/$(ABC048)/abc048B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc048B:	$(TEST_DIR)/$(ABC048)/test_abc048B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc048C:	$(SRC_DIR)/$(ABC048)/abc048C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc048C:	$(TEST_DIR)/$(ABC048)/test_abc048C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc048D:	$(SRC_DIR)/$(ABC048)/abc048D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc048D:	$(TEST_DIR)/$(ABC048)/test_abc048D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc049A:	$(SRC_DIR)/$(ABC049)/abc049A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc049A:	$(TEST_DIR)/$(ABC049)/test_abc049A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc049B:	$(SRC_DIR)/$(ABC049)/abc049B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc049B:	$(TEST_DIR)/$(ABC049)/test_abc049B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc049C:	$(SRC_DIR)/$(ABC049)/abc049C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc049C:	$(TEST_DIR)/$(ABC049)/test_abc049C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc049D:	$(SRC_DIR)/$(ABC049)/abc049D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc049D:	$(TEST_DIR)/$(ABC049)/test_abc049D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc050A:	$(SRC_DIR)/$(ABC050)/abc050A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc050A:	$(TEST_DIR)/$(ABC050)/test_abc050A.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc050B:	$(SRC_DIR)/$(ABC050)/abc050B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc050B:	$(TEST_DIR)/$(ABC050)/test_abc050B.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc050C:	$(SRC_DIR)/$(ABC050)/abc050C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc050C:	$(TEST_DIR)/$(ABC050)/test_abc050C.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

abc050D:	$(SRC_DIR)/$(ABC050)/abc050D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_abc050D:	$(TEST_DIR)/$(ABC050)/test_abc050D.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

clean:
	rm -f $(OBJS_ABC001) $(OBJS_ABC002) $(OBJS_ABC003) $(OBJS_ABC004) $(OBJS_ABC005) $(OBJS_ABC006) $(OBJS_ABC007) $(OBJS_ABC008) $(OBJS_ABC009) $(OBJS_ABC010) $(OBJS_ABC011) $(OBJS_ABC012) $(OBJS_ABC013) $(OBJS_ABC014) $(OBJS_ABC015) $(OBJS_ABC016) $(OBJS_ABC017) $(OBJS_ABC018) $(OBJS_ABC019) $(OBJS_ABC020) $(OBJS_ABC021) $(OBJS_ABC022) $(OBJS_ABC023) $(OBJS_ABC024) $(OBJS_ABC025) $(OBJS_ABC026) $(OBJS_ABC027) $(OBJS_ABC028) $(OBJS_ABC029) $(OBJS_ABC030) $(OBJS_ABC031) $(OBJS_ABC032) $(OBJS_ABC033) $(OBJS_ABC034) $(OBJS_ABC035) $(OBJS_ABC036) $(OBJS_ABC037) $(OBJS_ABC038) $(OBJS_ABC039) $(OBJS_ABC040) $(OBJS_ABC041) $(OBJS_ABC042) $(OBJS_ABC043) $(OBJS_ABC044) $(OBJS_ABC045) $(OBJS_ABC046) $(OBJS_ABC047) $(OBJS_ABC048) $(OBJS_ABC049) $(OBJS_ABC050)
