include ../CCOptions
OBJS=test_problem001 problem001 test_problem002 problem002 test_problem003 problem003 \
	test_problem004 problem004 test_problem005 problem005 test_problem006 problem006 \
	test_problem007 problem007 test_problem008 problem008 test_problem009 problem009 \
	test_problem010 problem010 test_problem011 problem011 test_problem012 problem012 \
	test_problem013 problem013 test_problem014 problem014 test_problem015 problem015 \
	test_problem016 problem016 test_problem017 problem017 test_problem018 problem018 \
	test_problem019 problem019 test_problem020 problem020 test_problem021 problem021 \
	test_problem022 problem022 test_problem023 problem023 test_problem024 problem024 \
	test_problem025 problem025 test_problem026 problem026 test_problem027 problem027 \
	test_problem028 problem028 test_problem029 problem029 test_problem030 problem030 \
	test_problem031 problem031 test_problem032 problem032 test_problem033 problem033 \
	test_problem034 problem034 test_problem034別回答 problem034別回答 test_problem035 problem035 test_problem036 problem036 \
	test_problem037 problem037 test_problem038 problem038 test_problem039 problem039 \
	test_problem040 problem040 test_problem041 problem041 test_problem042 problem042 \
	test_problem043 problem043 test_problem044 problem044 test_problem045 problem045 \
	test_problem046 problem046 test_problem047 problem047 test_problem048 problem048 \
	test_problem049 problem049 test_problem050 problem050 test_problem051 problem051 \
	test_problem052 problem052 test_problem053 problem053 test_problem054 problem054 \
	test_problem055 problem055 test_problem056 problem056 test_problem057 problem057 \
	test_problem058 problem058 test_problem059 problem059 test_problem060 problem060 \
	test_problem061 problem061 test_problem062 problem062 test_problem063 problem063 \
	test_problem064 problem064 test_problem065 problem065 test_problem066 problem066 \
	test_problem067 problem067 test_problem068 problem068 test_problem069 problem069 \
	test_problem070 problem070 test_problem071 problem071 test_problem072 problem072 \
	test_problem073 problem073 test_problem074 problem074 test_problem075 problem075 \
	test_problem076 problem076 test_problem077 problem077 test_problem078 problem078 \
	test_problem079 problem079 test_problem080 problem080 test_problem081 problem081 \
	test_problem082 problem082 test_problem083 problem083 test_problem084 problem084 \
	test_problem085 problem085 test_problem086 problem086 test_problem087 problem087 \
	test_problem088 problem088 test_problem089 problem089 test_problem090 problem090 \
	test_problem091 problem091 test_problem092 problem092 test_problem093 problem093 \
	test_problem094 problem094 test_problem095 problem095 test_problem096 problem096 \
	test_problem097 problem097 test_problem098 problem098 test_problem099 problem099 \
	test_problem100 problem100 test_problem101 problem101 test_problem102 problem102

all:	$(OBJS)

test_problem001: $(TEST_DIR)/test_problem001.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem001: $(SRC_DIR)/problem001.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem002: $(TEST_DIR)/test_problem002.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem002: $(SRC_DIR)/problem002.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem003: $(TEST_DIR)/test_problem003.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem003: $(SRC_DIR)/problem003.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem004: $(TEST_DIR)/test_problem004.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem004: $(SRC_DIR)/problem004.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem005: $(TEST_DIR)/test_problem005.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem005: $(SRC_DIR)/problem005.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem006: $(TEST_DIR)/test_problem006.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem006: $(SRC_DIR)/problem006.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem007: $(TEST_DIR)/test_problem007.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem007: $(SRC_DIR)/problem007.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem008: $(TEST_DIR)/test_problem008.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem008: $(SRC_DIR)/problem008.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem009: $(TEST_DIR)/test_problem009.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem009: $(SRC_DIR)/problem009.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem010: $(TEST_DIR)/test_problem010.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem010: $(SRC_DIR)/problem010.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem011: $(TEST_DIR)/test_problem011.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem011: $(SRC_DIR)/problem011.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem012: $(TEST_DIR)/test_problem012.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem012: $(SRC_DIR)/problem012.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem013: $(TEST_DIR)/test_problem013.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem013: $(SRC_DIR)/problem013.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem014: $(TEST_DIR)/test_problem014.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem014: $(SRC_DIR)/problem014.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem015: $(TEST_DIR)/test_problem015.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem015: $(SRC_DIR)/problem015.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem016: $(TEST_DIR)/test_problem016.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem016: $(SRC_DIR)/problem016.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem017: $(TEST_DIR)/test_problem017.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem017: $(SRC_DIR)/problem017.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem018: $(TEST_DIR)/test_problem018.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem018: $(SRC_DIR)/problem018.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem019: $(TEST_DIR)/test_problem019.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem019: $(SRC_DIR)/problem019.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem020: $(TEST_DIR)/test_problem020.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem020: $(SRC_DIR)/problem020.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem021: $(TEST_DIR)/test_problem021.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem021: $(SRC_DIR)/problem021.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem022: $(TEST_DIR)/test_problem022.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem022: $(SRC_DIR)/problem022.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem023: $(TEST_DIR)/test_problem023.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem023: $(SRC_DIR)/problem023.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem024: $(TEST_DIR)/test_problem024.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem024: $(SRC_DIR)/problem024.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem025: $(TEST_DIR)/test_problem025.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem025: $(SRC_DIR)/problem025.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem026: $(TEST_DIR)/test_problem026.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem026: $(SRC_DIR)/problem026.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem027: $(TEST_DIR)/test_problem027.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem027: $(SRC_DIR)/problem027.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem028: $(TEST_DIR)/test_problem028.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem028: $(SRC_DIR)/problem028.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem029: $(TEST_DIR)/test_problem029.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem029: $(SRC_DIR)/problem029.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem030: $(TEST_DIR)/test_problem030.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem030: $(SRC_DIR)/problem030.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem031: $(TEST_DIR)/test_problem031.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem031: $(SRC_DIR)/problem031.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem032: $(TEST_DIR)/test_problem032.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem032: $(SRC_DIR)/problem032.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem033: $(TEST_DIR)/test_problem033.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem033: $(SRC_DIR)/problem033.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem034: $(TEST_DIR)/test_problem034.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem034: $(SRC_DIR)/problem034.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem034別回答: $(TEST_DIR)/test_problem034別回答.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem034別回答: $(SRC_DIR)/problem034別回答.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem035: $(TEST_DIR)/test_problem035.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem035: $(SRC_DIR)/problem035.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem036: $(TEST_DIR)/test_problem036.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem036: $(SRC_DIR)/problem036.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem037: $(TEST_DIR)/test_problem037.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem037: $(SRC_DIR)/problem037.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem038: $(TEST_DIR)/test_problem038.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem038: $(SRC_DIR)/problem038.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem039: $(TEST_DIR)/test_problem039.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem039: $(SRC_DIR)/problem039.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem040: $(TEST_DIR)/test_problem040.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem040: $(SRC_DIR)/problem040.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem041: $(TEST_DIR)/test_problem041.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem041: $(SRC_DIR)/problem041.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem042: $(TEST_DIR)/test_problem042.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem042: $(SRC_DIR)/problem042.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem043: $(TEST_DIR)/test_problem043.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem043: $(SRC_DIR)/problem043.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem044: $(TEST_DIR)/test_problem044.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem044: $(SRC_DIR)/problem044.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem045: $(TEST_DIR)/test_problem045.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem045: $(SRC_DIR)/problem045.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem046: $(TEST_DIR)/test_problem046.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem046: $(SRC_DIR)/problem046.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem047: $(TEST_DIR)/test_problem047.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem047: $(SRC_DIR)/problem047.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem048: $(TEST_DIR)/test_problem048.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem048: $(SRC_DIR)/problem048.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem049: $(TEST_DIR)/test_problem049.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem049: $(SRC_DIR)/problem049.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem050: $(TEST_DIR)/test_problem050.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem050: $(SRC_DIR)/problem050.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem051: $(TEST_DIR)/test_problem051.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem051: $(SRC_DIR)/problem051.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem052: $(TEST_DIR)/test_problem052.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem052: $(SRC_DIR)/problem052.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem053: $(TEST_DIR)/test_problem053.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem053: $(SRC_DIR)/problem053.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem054: $(TEST_DIR)/test_problem054.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem054: $(SRC_DIR)/problem054.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem055: $(TEST_DIR)/test_problem055.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem055: $(SRC_DIR)/problem055.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem056: $(TEST_DIR)/test_problem056.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem056: $(SRC_DIR)/problem056.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem057: $(TEST_DIR)/test_problem057.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem057: $(SRC_DIR)/problem057.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem058: $(TEST_DIR)/test_problem058.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem058: $(SRC_DIR)/problem058.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem059: $(TEST_DIR)/test_problem059.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem059: $(SRC_DIR)/problem059.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem060: $(TEST_DIR)/test_problem060.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem060: $(SRC_DIR)/problem060.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem061: $(TEST_DIR)/test_problem061.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem061: $(SRC_DIR)/problem061.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem062: $(TEST_DIR)/test_problem062.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem062: $(SRC_DIR)/problem062.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem063: $(TEST_DIR)/test_problem063.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem063: $(SRC_DIR)/problem063.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem064: $(TEST_DIR)/test_problem064.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem064: $(SRC_DIR)/problem064.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem065: $(TEST_DIR)/test_problem065.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem065: $(SRC_DIR)/problem065.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem066: $(TEST_DIR)/test_problem066.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem066: $(SRC_DIR)/problem066.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem067: $(TEST_DIR)/test_problem067.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem067: $(SRC_DIR)/problem067.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem068: $(TEST_DIR)/test_problem068.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem068: $(SRC_DIR)/problem068.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem069: $(TEST_DIR)/test_problem069.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem069: $(SRC_DIR)/problem069.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem070: $(TEST_DIR)/test_problem070.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem070: $(SRC_DIR)/problem070.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem071: $(TEST_DIR)/test_problem071.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem071: $(SRC_DIR)/problem071.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem072: $(TEST_DIR)/test_problem072.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem072: $(SRC_DIR)/problem072.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem073: $(TEST_DIR)/test_problem073.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem073: $(SRC_DIR)/problem073.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem074: $(TEST_DIR)/test_problem074.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem074: $(SRC_DIR)/problem074.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem075: $(TEST_DIR)/test_problem075.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem075: $(SRC_DIR)/problem075.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem076: $(TEST_DIR)/test_problem076.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem076: $(SRC_DIR)/problem076.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem077: $(TEST_DIR)/test_problem077.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem077: $(SRC_DIR)/problem077.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem078: $(TEST_DIR)/test_problem078.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem078: $(SRC_DIR)/problem078.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem079: $(TEST_DIR)/test_problem079.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem079: $(SRC_DIR)/problem079.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem080: $(TEST_DIR)/test_problem080.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem080: $(SRC_DIR)/problem080.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem081: $(TEST_DIR)/test_problem081.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem081: $(SRC_DIR)/problem081.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem082: $(TEST_DIR)/test_problem082.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem082: $(SRC_DIR)/problem082.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem083: $(TEST_DIR)/test_problem083.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem083: $(SRC_DIR)/problem083.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem084: $(TEST_DIR)/test_problem084.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem084: $(SRC_DIR)/problem084.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem085: $(TEST_DIR)/test_problem085.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem085: $(SRC_DIR)/problem085.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem086: $(TEST_DIR)/test_problem086.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem086: $(SRC_DIR)/problem086.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem087: $(TEST_DIR)/test_problem087.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem087: $(SRC_DIR)/problem087.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem088: $(TEST_DIR)/test_problem088.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem088: $(SRC_DIR)/problem088.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem089: $(TEST_DIR)/test_problem089.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem089: $(SRC_DIR)/problem089.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem090: $(TEST_DIR)/test_problem090.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem090: $(SRC_DIR)/problem090.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem091: $(TEST_DIR)/test_problem091.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem091: $(SRC_DIR)/problem091.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem092: $(TEST_DIR)/test_problem092.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem092: $(SRC_DIR)/problem092.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem093: $(TEST_DIR)/test_problem093.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem093: $(SRC_DIR)/problem093.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem094: $(TEST_DIR)/test_problem094.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem094: $(SRC_DIR)/problem094.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem095: $(TEST_DIR)/test_problem095.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem095: $(SRC_DIR)/problem095.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem096: $(TEST_DIR)/test_problem096.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem096: $(SRC_DIR)/problem096.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem097: $(TEST_DIR)/test_problem097.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem097: $(SRC_DIR)/problem097.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem098: $(TEST_DIR)/test_problem098.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem098: $(SRC_DIR)/problem098.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem099: $(TEST_DIR)/test_problem099.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem099: $(SRC_DIR)/problem099.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem100: $(TEST_DIR)/test_problem100.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem100: $(SRC_DIR)/problem100.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem101: $(TEST_DIR)/test_problem101.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem101: $(SRC_DIR)/problem101.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

test_problem102: $(TEST_DIR)/test_problem102.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE) $(LIBS)

problem102: $(SRC_DIR)/problem102.cpp
	$(CC) $(CFLAGS) $(^) -o $(@) $(INCLUDE)

clean:
	rm -f $(OBJS)

