ABC051=abc051
ABC052=abc052
ABC053=abc053
ABC054=abc054
ABC055=abc055
ABC056=abc056
ABC057=abc057
ABC058=abc058
ABC059=abc059
ABC060=abc060
ABC061=abc061
ABC062=abc062
ABC063=abc063
ABC064=abc064
ABC065=abc065
ABC066=abc066
ABC067=abc067
ABC068=abc068
ABC069=abc069
ABC070=abc070
ABC071=abc071
ABC072=abc072
ABC073=abc073
ABC074=abc074
ABC075=abc075
ABC076=abc076
ABC077=abc077
ABC078=abc078
ABC079=abc079
ABC080=abc080
ABC081=abc081
ABC082=abc082
ABC083=abc083
ABC084=abc084
ABC085=abc085
ABC086=abc086
ABC087=abc087
ABC088=abc088
ABC089=abc089
ABC090=abc090
ABC091=abc091
ABC092=abc092
ABC093=abc093
ABC094=abc094
ABC095=abc095
ABC096=abc096
ABC097=abc097
ABC098=abc098
ABC099=abc099
ABC100=abc100

all:	_$(ABC051) _$(ABC052) _$(ABC053) _$(ABC054) _$(ABC055) #_$(ABC056) _$(ABC057) _$(ABC058) _$(ABC059) _$(ABC060) _$(ABC061) _$(ABC062) _$(ABC063) _$(ABC064) _$(ABC065) _$(ABC066) _$(ABC067) _$(ABC068) _$(ABC069) _$(ABC070) _$(ABC071) _$(ABC072) _$(ABC073) _$(ABC074) _$(ABC075) _$(ABC076) _$(ABC077) _$(ABC078) _$(ABC079) _$(ABC080) _$(ABC081) _$(ABC082) _$(ABC083) _$(ABC084) _$(ABC085) _$(ABC086) _$(ABC087) _$(ABC088) _$(ABC089) _$(ABC090) _$(ABC091) _$(ABC092) _$(ABC093) _$(ABC094) _$(ABC095) _$(ABC096) _$(ABC097) _$(ABC098) _$(ABC099) _$(ABC100)

_$(ABC051):
	make -C $(ABC051)

_$(ABC052):
	make -C $(ABC052)

_$(ABC053):
	make -C $(ABC053)

_$(ABC054):
	make -C $(ABC054)

_$(ABC055):
	make -C $(ABC055)

_$(ABC056):
	make -C $(ABC056)

_$(ABC057):
	make -C $(ABC057)

_$(ABC058):
	make -C $(ABC058)

_$(ABC059):
	make -C $(ABC059)

_$(ABC060):
	make -C $(ABC060)

_$(ABC061):
	make -C $(ABC061)

_$(ABC062):
	make -C $(ABC062)

_$(ABC063):
	make -C $(ABC063)

_$(ABC064):
	make -C $(ABC064)

_$(ABC065):
	make -C $(ABC065)

_$(ABC066):
	make -C $(ABC066)

_$(ABC067):
	make -C $(ABC067)

_$(ABC068):
	make -C $(ABC068)

_$(ABC069):
	make -C $(ABC069)

_$(ABC070):
	make -C $(ABC070)

_$(ABC071):
	make -C $(ABC071)

_$(ABC072):
	make -C $(ABC072)

_$(ABC073):
	make -C $(ABC073)

_$(ABC074):
	make -C $(ABC074)

_$(ABC075):
	make -C $(ABC075)

_$(ABC076):
	make -C $(ABC076)

_$(ABC077):
	make -C $(ABC077)

_$(ABC078):
	make -C $(ABC078)

_$(ABC079):
	make -C $(ABC079)

_$(ABC080):
	make -C $(ABC080)

_$(ABC081):
	make -C $(ABC081)

_$(ABC082):
	make -C $(ABC082)

_$(ABC083):
	make -C $(ABC083)

_$(ABC084):
	make -C $(ABC084)

_$(ABC085):
	make -C $(ABC085)

_$(ABC086):
	make -C $(ABC086)

_$(ABC087):
	make -C $(ABC087)

_$(ABC088):
	make -C $(ABC088)

_$(ABC089):
	make -C $(ABC089)

_$(ABC090):
	make -C $(ABC090)

_$(ABC091):
	make -C $(ABC091)

_$(ABC092):
	make -C $(ABC092)

_$(ABC093):
	make -C $(ABC093)

_$(ABC094):
	make -C $(ABC094)

_$(ABC095):
	make -C $(ABC095)

_$(ABC096):
	make -C $(ABC096)

_$(ABC097):
	make -C $(ABC097)

_$(ABC098):
	make -C $(ABC098)

_$(ABC099):
	make -C $(ABC099)

_$(ABC100):
	make -C $(ABC100)

clean:
	make -C $(ABC051) clean
	make -C $(ABC052) clean
	make -C $(ABC053) clean
	make -C $(ABC054) clean
	make -C $(ABC055) clean
#	make -C $(ABC056) clean
#	make -C $(ABC057) clean
#	make -C $(ABC058) clean
#	make -C $(ABC059) clean
#	make -C $(ABC060) clean
#	make -C $(ABC061) clean
#	make -C $(ABC062) clean
#	make -C $(ABC063) clean
#	make -C $(ABC064) clean
#	make -C $(ABC065) clean
#	make -C $(ABC066) clean
#	make -C $(ABC067) clean
#	make -C $(ABC068) clean
#	make -C $(ABC069) clean
#	make -C $(ABC070) clean
#	make -C $(ABC071) clean
#	make -C $(ABC072) clean
#	make -C $(ABC073) clean
#	make -C $(ABC074) clean
#	make -C $(ABC075) clean
#	make -C $(ABC076) clean
#	make -C $(ABC077) clean
#	make -C $(ABC078) clean
#	make -C $(ABC079) clean
#	make -C $(ABC080) clean
#	make -C $(ABC081) clean
#	make -C $(ABC082) clean
#	make -C $(ABC083) clean
#	make -C $(ABC084) clean
#	make -C $(ABC085) clean
#	make -C $(ABC086) clean
#	make -C $(ABC087) clean
#	make -C $(ABC088) clean
#	make -C $(ABC089) clean
#	make -C $(ABC090) clean
#	make -C $(ABC091) clean
#	make -C $(ABC092) clean
#	make -C $(ABC093) clean
#	make -C $(ABC094) clean
#	make -C $(ABC095) clean
#	make -C $(ABC096) clean
#	make -C $(ABC097) clean
#	make -C $(ABC098) clean
#	make -C $(ABC099) clean
#	make -C $(ABC100) clean
